### ISSUE TITLE
"os.time()" should return a random time when the computer is in the nether

### ISSUE THREAD

**Issue by Flexico** [SquidDev-CC/CC-Tweaked#1142]
When  a computer/turtle is in the Nether, End, or anywhere a vanilla clock would spin randomly, the os.time() function should also return a random number 0 <= t < 24.

**Comment by Lupus590** [comment]
I like the idea but I do wonder how much of a problem this might cause for backwards compatability.

**Comment by Flexico** [comment]
Yeah, that could be an issue!

**Comment by Sirian142** [comment]
In my opinion a creative idea, but I believe vanilla clocks and compasses in the nether and end could (scientifically) be a result of magnetic anomalies rather than the concept of time missing, which means computers can still calculate with tech magic if clocks cannot. (You could always get more technical with this theory with magnetism ruining the entire computer, alternate dimension + clock theory ideas, etc but that's a big rabbit hole).

**Additionally and more importantly,** this may simply mess up a lot of programs and be a general hindrance to many players who just want to run a program in another dimension for whatever reason.

**Comment by SquidDev** [comment]
Afraid I'm going to close this. I think it's a fun idea, but I don't think justifiable enough to be worth the issues it introduces.
