### ISSUE TITLE
Crashes server with create mod

### ISSUE THREAD

**Issue by IThundxr** [SquidDev-CC/CC-Tweaked#1178]
### Minecraft Version

1.18.x

### Version

N/A

### Details

https://github.com/Creators-of-Create/Create/issues/3751 issue that should be fixed cc: tweaked side

**Comment by SquidDev** [comment]
`Item.isBarVisible` is not marked client only (as of 1.17 I don't believe anything outside of the client packages is client-only). The problem here is that Create's `BackTankUtil.isBarVisible` is marked as client-only.

https://github.com/Creators-of-Create/Create/blob/c7a75f8ffd01e09eea68be827d296030da56ca4c/src/main/java/com/simibubi/create/content/curiosities/armor/BackTankUtil.java#L108-L109

I'll switch over to `isDamaged`/`isDamageableItem`. here to avoid this, but it's probably worth seeing how this can be resolved on the Create end too.

**Comment by IThundxr** [comment]
I'll send this bug report to create aswell

**Comment by SquidDev** [comment]
> I'll switch over to isDamaged/isDamageableItem. here to avoid this

I lied. Looking over the code again, I think the current behaviour is correct.

**Comment by IThundxr** [comment]
Let simi know about this issue hopefully it gets fixed

**Comment by caelwarner** [comment]
Fixed by Creators-of-Create/Create@0c5ccf38ee15f446f385290f2238f2ae975681cd

**Comment by IThundxr** [comment]
> Fixed by Creators-of-Create/Create@0c5ccf38ee15f446f385290f2238f2ae975681cd

Just wondering doesn't this affect potato cannon aswell?

**Comment by caelwarner** [comment]
It doesn't affect the normal usage of the potato cannon. It fixes the potato cannon causing a crash when calling `turtle.getItemDetail()` on a dedicated server. Does that answer your question?

**Comment by IThundxr** [comment]
> It doesn't affect the normal usage of the potato cannon. It fixes the potato cannon causing a crash when calling `turtle.getItemDetail()` on a dedicated server. Does that answer your question?

Yes
