### ISSUE TITLE
1 does not equal 1?

### ISSUE THREAD

**Issue by ThinkingBeanz** [SquidDev-CC/CC-Tweaked#1225]
### Minecraft Version

1.18.x

### Version

1.101.0

### Details

I'm facing a weird bug. (31.36 * 64)/(44.8^2) should equal 1, but it doesnt?
I'm on version 1.18.2 of Minecraft, using CC:Tweaked version 1.101.0 on Forge version 40.1.84

printing (31.36 * 64) / (44.8 ^ 2) says 1, but when compared with 1 using the "==" operator, it prints "false".
My main issue is I'm trying to get the inverse sine of the number, but it returns "nan", even though it works if I input 1.
![image](https://user-images.githubusercontent.com/110514609/203373886-c6f55d76-5e72-405e-aa9e-2ef317829b16.png)
![image](https://user-images.githubusercontent.com/110514609/203374007-ae956639-d7dc-492b-b151-ad40670bb19e.png)
![image](https://user-images.githubusercontent.com/110514609/203374117-8591e6ef-68aa-4803-9719-962753b5510e.png)
![image](https://user-images.githubusercontent.com/110514609/203374274-40972c73-ae77-40e2-917d-096a3f5cafcf.png)

The main issue is I'm working on some sorta program that finds the angle given a distance from a cannon, but I get nan when trying to get an angle at the max range of the cannon given parameters. I am using the Create mod alongside Big Cannons, an addon for the Create mod.

**Comment by Kan18** [comment]
The problem here is with IEEE 754 double-precision floating point numbers not being able to precisely represent some numbers. 

You could try `tonumber(tostring((31.36*64)/(44.8^2)))`. (The number gets rounded down to 1 when `tostring` is called.)
Alternatively, keep it within the domain of `math.asin`  through using `math.min` and `math.max`: `math.min(1, math.max(-1, (31.36*64)/(44.8^2)))`

**Comment by ThinkingBeanz** [comment]
Thank you for the idea. Never thought of converting it to a string and then back to a number!
