### ISSUE TITLE
Dinnerbone/Grumm turtle easter egg causes render issues

### ISSUE THREAD

**Issue by MineRobber9000** [SquidDev-CC/CC-Tweaked#1283]
### Minecraft Version

1.19.x

### Version

1.102.0

### Details

Title. The easter egg (which flips turtles named "Dinnerbone" or "Grumm" upside down, much like mobs or the players themselves) renders the three faces that would be visible if the turtle were right-side-up, instead of the faces that should be visible from the user's current perspective.

![Turtle named Grumm](https://user-images.githubusercontent.com/12676241/210125652-d925f307-e459-4608-8889-c6ce82730f55.png)

![Turtle named Dinnerbone](https://user-images.githubusercontent.com/12676241/210125654-12d809c1-5041-4639-9e34-1abaf59cfdc6.png)

**To reproduce:**

1. Label a turtle "Dinnerbone" or "Grumm".
2. Observe rendering bug.

**Comment by SquidDev** [comment]
Yeah, this has been broken since 1.8 from memory, ever since the rendering rework. The problem here is that flipping the turtle changes the direction of the quad, so the wrong one gets culled.

Turning off culling is not sufficient as the normals are still wrong. I think what we probably need to do is reverse of the vertexes (both in the BER and the item model).

**Comment by walksanatora** [comment]
am i the only one that likes inverted turtle
