### ISSUE TITLE
Command block peripheral suggestion

### ISSUE THREAD

**Issue by awesomebossdj7** [SquidDev-CC/CC-Tweaked#1312]
Allow the Command Block peripheral to be able to attach to turtles and pocket computers
(Which would work like if a computer had a command peripheral)

Alternatively add a command block version of a Pocket computer and Turtle (like computers)
(Which would work like the command version of the computer)

**Comment by awesomebossdj7** [comment]
Imagine commanding turtle or command block pocket computer

**Comment by SquidDev** [comment]
I'm afraid I'm probably not going to implement this.

While there is some merit in being consistent in what gets a "Command" version and what doesn't, I'm not actually sure it's otherwise a worthwhile feature. Command computers are mostly a admin/creative only tool, and so there's not really any context where having a command turtle is useful.

Command pocket computers might be a little more useful, I just think it's sufficiently niche that it's not worth implementing right now.

**Comment by Lupus590** [comment]
With command computers being admin/creative tools, if one wants a creative pocket computer and/or turtle then one can use the give command to give themselves two computers with the same ID (one of these being the command computer and the other being the turtle/pocket computer). The two computers now sharing an ID also share a file system, giving a secure way for the two to communicate. Then you just need to push any command API usage to the actual command computer via the file system so that the actual command computer can read it.

**Comment by awesomebossdj7** [comment]
> I'm afraid I'm probably not going to implement this.
> 
> While there is some merit in being consistent in what gets a "Command" version and what doesn't, I'm not actually sure it's otherwise a worthwhile feature. Command computers are mostly a admin/creative only tool, and so there's not really any context where having a command turtle is useful.
> 
> Command pocket computers might be a little more useful, I just think it's sufficiently niche that it's not worth implementing right now.


i mean is there really a use for any of them to exist? command computers are only good for 1.12 cuz no datapacks
