### ISSUE TITLE
Game crashes when placing a turtle

### ISSUE THREAD

**Issue by User3624** [SquidDev-CC/CC-Tweaked#1325]
### Minecraft Version

1.19.x

### Version

1.101.1

### Details

Reproduction steps:
1. Place down a turtle in any world.
Logs:
[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/10679244/latest.log)

**Comment by SquidDev** [comment]
See #1239. This is an Optifine bug: they don't support the latest version of Forge. You can probably downgrade to Forge 43.1.1, though really I'd recommend [switching to Occulus](https://modrinth.com/mod/oculus) instead.

**Comment by User3624** [comment]
The turtles stopped working mysteriously, they used to work.
The same enviorement.

**Comment by User3624** [comment]
Older versions of forge are incompatible with mods that are being used.

**Comment by User3624** [comment]
One thing;
The game only crashes when placing a turtle, and not computers. Computers are blocks with UI as well, and they are technically block entities as well.

**Comment by User3624** [comment]
ah wait no one cares anyway

**Comment by User3624** [comment]
older forge does not boot up.

**Comment by User3624** [comment]
probably mod incompatiblibylty

**Comment by User3624** [comment]
where is the delete issue button?

**Comment by SquidDev** [comment]
You might be able to switch to Forge 43.1.52 as long as you're running OptiFine HD U I1. You have to be careful to run the exact version of Forge [mentioned on OptiFine's download page](https://optifine.net/downloads), otherwise you'll occasionally run into issues like these.

Though I'd also recommend looking into the various Optifine alternatives out there. Optifine is notoriously prone to issues like these - mods like [Oculus](https://modrinth.com/mod/oculus) for shaders and [Rubidium](https://modrinth.com/mod/rubidium) are much better supported.
