### ISSUE TITLE
[FABRIC] Handheld pocket computers render in grayscale

### ISSUE THREAD

**Issue by scmcgowen** [SquidDev-CC/CC-Tweaked#1347]
### Minecraft Version

1.19.x

### Version

1.100.3

### Details

Expected colors:
![image](https://user-images.githubusercontent.com/34895975/220823114-75f97ee3-278a-4e29-966c-59c999fa88b9.png)

I get these colors:
![image](https://user-images.githubusercontent.com/34895975/220823129-5e67a178-8b5e-44fb-bbe1-fe8b54e179fd.png)

**Comment by SquidDev** [comment]
Hrmr, that's very odd: Fabric (top) and Forge (bottom) appear identical for me.

![A screenshot of a two Minecraft windows, both holding a pocket computer. Both computers render in colour.](https://user-images.githubusercontent.com/4346137/220852348-83ca5779-63bd-41e9-94c8-d4430ca90385.png)

Does this happen repeatedly (i.e. across world restarts, or for multiple pocket computers?). I'm wondering if this is a desync issue, rather than a loader-specific issue.

Would you be able to attach your logs?

**Comment by MCJack123** [comment]
Important to note is that this affects the computer *in the offhand* - from what I can tell, it's fine in the main hand as you described.

**Comment by scmcgowen** [comment]
The consistent way I've found to reproduce it with the SC modpack is:
```
Step 1: Join the SwitchCraft server
Step 2: Disconnect from the server
Step 3: open singleplayer world 
Step 4: pull up a pocket computer
```

**Comment by scmcgowen** [comment]
And yes, it does happen across world relogs but restarting the game fixes it
