### ISSUE TITLE
"Resurrection" of bedrock fork

### ISSUE THREAD

**Issue by vico93** [SquidDev-CC/CC-Tweaked#1353]
Really sorry to open it on this repo, since https://github.com/SquidDev-CC/bedrock is archived i cannot open an issue on there.

BTW, talking with some guys that work with Bedrock's behavior packs, they said to me that the addon "api" really got "expanded up" since the last time the bedrock "fork" was updated.

So, what about trying that fork again? I know that was just a proof-of-concept and you guys are already maintaing versions of CC:T for Forge and Fabric, but a Bedrock version would renew interest in the mod, a̵n̵d̵ ̵a̵l̵l̵o̵w̵ ̵m̵e̵ ̵t̵o̵ ̵f̵u̵l̵l̵y̵ ̵s̵w̵i̵t̵c̵h̵ ̵f̵r̵o̵m̵ ̵J̵a̵v̵a̵ ̵1̵.̵1̵2̵ ̵t̵o̵ ̵B̵e̵d̵r̵o̵c̵k̵ ̵o̵n̵c̵e̵ ̵f̵o̵r̵ ̵a̵l̵l̵.

**Comment by SquidDev** [comment]
I've only had a quick skim through the bedrock docs and, while things are much improve, there's definitely too many missing features to make it feasible:

 - One main issue is that Bedrock using QuickJS under the hood. QuickJS is cool, but it's an order of magnitude[^1] slower than the Javascript engines seen in a browser. This just makes it impractical to run CC in.

   Really CC needs JIT-based JS engine or support for WASM. Ideally also the ability to run work on a separate thread, but we can get around that.

 - A more flexible UI library: It looks [like this is in the works](https://github.com/Mojang/ore-ui), but it's still stuck on the JSON-based system right now. The old bedrock version used the previous HTML UI system, but that's long gone.

 - Far more flexible block behaviours: from what I can tell there's no way to make a block emit redstone (or rather, emit redstone dynamically), which means that even if computers were usable they wouldn't be able to do anything.

   We _could_ do turtles, though the lack of block entity renderers would mean that they'd have no animation :(.

   I guess the other alternative there would just be to make them entities rather than blocks, like [the MCEdu Agent](https://minecraft.fandom.com/wiki/Agent).

[^1]: According [to QuickJs's benchmarks](https://bellard.org/quickjs/bench.html), it's 35x slower than V8.

**Comment by SquidDev** [comment]
> allow me to switch from 1.12 Java

At least do yourself a favour and update to 1.19!

**Comment by vico93** [comment]
> > allow me to switch from 1.12 Java
> 
> At least do yourself a favour and update to 1.19!

Would love to do that if the author of [TrainCarts](https://github.com/bergerhealer/TrainCarts) plugin doesnt see a native port to Fabric as out of plans, forcing me to stay on 1.12 basically because this is the last playable version of Forge (for me) and there is no hybrid servers Spigot <> Fabric that are able to run that plugin.

But this is another story...
