### ISSUE TITLE
Support more colors

### ISSUE THREAD

**Issue by vaxerski** [SquidDev-CC/CC-Tweaked#1363]
Sorry if this has been suggested before, checked the issue tracker, didnt find anything.

I'd like to request support for more colors, at least 256 colors.

Images or rendering is extremely limited and looks terrible with 16 colors. Even the GIF format made for the era of early 90s has 256 colors.

I've seen the suggestion about 0.25 scale and the argument was that it'd increase the data size. Going from 16 colors to 256 would technically double the data sent (from 4bpp to 8bpp) but I feel like it's an option that at least should be configurable.

E.g. a server could have a config option to "enable 256 color mode".

Furthermore, 328 * 243 / 1024 ≈ 80 KiB, which in the modern world, let's face it, is nothing. The world is going to have way more data to send.

**Comment by piprett** [comment]
I'm not sure how I feel about this. 

> Images or rendering is extremely limited and looks terrible with 16 colors. Even the GIF format made for the era of early 90s has 256 colors.

 I wouldn't say this "looks terrible".
![image](https://user-images.githubusercontent.com/49862976/223938700-50bfa9af-7d0e-4ba4-9027-b2cc1f208c70.png)

The 16 customizable colors, adds a piece of difficulty to big programs in my opinion. And you don't need more than 16 colors to make cool UIs. I feel like 256 colors wouldn't fit the vibe of CC.

**Comment by vaxerski** [comment]
"not fitting the vibe" is one of those arguments that doesn't really make sense. Why not add it behind a config opt that's `false` by default then?

> I wouldn't say this "looks terrible".

I would. I wanted to render some images that I can show once I get to my computer, but they were barely recognizable, even more than yours.

**Comment by SquidDev** [comment]
The limited palette depth is an intentional restriction. ComputerCraft is meant to mimic the aesthetic of retro-computers (I think specifically the BBC Micro), and so inherits some of its limitations.

Personally, I think that's fine. While you can't just convert arbitrary images to CC's limited palette and expect them to work, it's still possible to create good looking images, it just takes some time[^1].


[^1]: Even with CC's limited resolutions, [the images in this tweet](https://twitter.com/gamepresintl/status/1311500905938780166), do [look pretty good](https://user-images.githubusercontent.com/4346137/224268361-aa66a345-2a94-4230-9a46-6d8dd5ba0f93.png).
