### ISSUE TITLE
When place turtles explodes: it crash and can't join anymore.

### ISSUE THREAD

**Issue by AndreaSciscioli** [SquidDev-CC/CC-Tweaked#1383]
### Minecraft Version

1.19.x

### Version
1.101.2

### Details

The game saves and come back to desktop. That's only on client becouse the server continue running

**Comment by SquidDev** [comment]
Would you be able to post your crash log?

**Comment by SquidDev** [comment]
Closing as without a crash report there's very little I can do. I _suspect_ this issue is caused by Optifine - see #1239. When [downloading Optifine](https://optifine.net/downloads), make sure you're running the _exact_ version of Forge recommended there.

That said, I'd really recommend [replacing Optifine with Occulus](https://modrinth.com/mod/oculus).
