### ISSUE TITLE
Strange crash when trying to boot a dedicated server

### ISSUE THREAD

**Issue by vico93** [SquidDev-CC/CC-Tweaked#1431]
### Minecraft Version

1.19.x

### Version

1.104.0

### Details

Well, after assembling my modpack on client, i decided to do a quick test on dedicated server to see if something was amiss.

Unfortunately the server crashed with [this log](https://gist.github.com/vico93/936c571ef2697b98fde19aa0467b2166), that i assume can be something on cc-t site.

**Comment by SquidDev** [comment]
Thanks for the report!

This is very odd - CC:T definitely works on a dedicated server after all! My hunch here is that some mod is also touching log4j and the two mods conflict, but I've no clue what's actually causing this. It might be worth you narrowing this down to a minimal set of mods, so it's easier to look into the root cause.

**Comment by vico93** [comment]
I started removing one by one mod on my dedicated server end, and when i removed [c2me](https://github.com/RelativityMC/C2ME-fabric/) the issue seems to have vanished (althrough i still have some other error lines related to other mods).

I will open an issue on their repository about it.
