### ISSUE TITLE
Ability to Focus CC Monitors for Enhanced User Experience

### ISSUE THREAD

**Issue by MonoToast** [SquidDev-CC/CC-Tweaked#1470]
Feature Request:

Description: 

I want to propose the addition of a new feature to the CC Tweaked. The feature I'm suggesting is the ability to focus ComputerCraft monitors, which greatly enhances the user experience by unlocking the mouse and enabling keyboard input. This functionality would open up various possibilities.

Details:

Sneak Right Click or Custom Key Binding: The proposed feature should be activated by pressing the activation key while looking at the CC monitor. 

Focused Monitor Mode: When a user successfully focuses a CC monitor, it should enter a "focused monitor" mode, where the mouse cursor is freed allowing the player to click on the monitor.

Keyboard Input: In the "focused monitor" mode, users should be able to use their keyboard and the computer would receive keyboard events, enabling them to interact with programs running on the Computer.

Benefits:

Enhanced User Interaction: Enabling the focus feature will allow users to have a more immersive and interactive experience with CC monitors. They can input commands, navigate menus, or play games on the monitor.

Improved Usability for Larger Terminals: With the ability to focus CC monitors, users can create larger terminal displays, which would be particularly beneficial for complex programs or when working with large amounts of data.

Expanded Gaming Possibilities: The focus feature will unlock new possibilities for gaming on CC monitors. Users can create more interactive and dynamic games by incorporating keyboard input alongside the visual elements.

Implementation Considerations:

User Interface: Consider adding a visual indication when a CC monitor is in the "focused monitor" mode, such as changing the border color or displaying an overlay on the monitor screen.

Configuration Options: Provide configurable options in the mod's configuration file to allow users to customize key bindings and adjust additional settings related to the focus feature.

Conclusion:

Overall, implementing the ability to focus CC monitors would greatly improve the usability and versatility of the CC Tweaked mod, enhancing the user experience and opening up new creative possibilities for both programming and gaming within Minecraft.

**Comment by SquidDev** [comment]
Thank you for the detailed issue! I've spent some time thinking about this, and I'm afraid I'm going to mark this as "won't fix".

One of the things I really like about monitors is that they're one of the few blocks in the mod that you exclusively interact with in inside the game world, rather than in a GUI. I definitely understand the motivation, but also I think adding a UI here is a rather boring solution to this problem!

For keyboard interaction, you can do the same thing with an off-hand pocket computer and rednet. It's definitely a bit more code, but also more flexible (supports multi-monitor setups for instance).

Mouse movement is more tricky to solve. You can of course right-click the monitor (though doing that within the off-hand pocket computer no longer works as of 1.20), but it's not super nice to do a lot.
