### ISSUE TITLE
`)(` is accepted as valid input to the REPL

### ISSUE THREAD

**Issue by khankul** [SquidDev-CC/CC-Tweaked#1506]
### Minecraft Version

1.20.x

### Version

1.105.0

### Details

1. Launch a Lua shell
2. Input `print)(` and hit Enter
3. ` `
`1`

It also works with functions like `exit` and `term.clear`.
For comparison, 
PUC 5.4.4: `syntax error near ')'`
LuaJIT 2.1.0-beta3: `'=' expected near ')'`

I thought it might be a Cobalt issue, so I wrote a simple test (the same print statement) for it, but it crashes with `CompileException: '=' expected near ')'` so it has to be CC related.

**Comment by Wojbie** [comment]
This issue is caused by `lua` prompt logic itself and not Cobalt related. 
This is lines that cause it: 
https://github.com/cc-tweaked/CC-Tweaked/blob/34f41c4039dab6a4fe05d9b5d9c3f2731e32b0f5/projects/core/src/main/resources/data/computercraft/lua/rom/programs/lua.lua#L78-L90
This is side effect of `lua` prompt trying to echo a value that user entered if they just enter for example a string without any execution. In this case loaded string becomes `return _echo(print)();` which cause _echo just returns all its arguments becomes valid `print()` call.
