### ISSUE TITLE
Generic peripheral overhaul suggestion

### ISSUE THREAD

**Issue by SirEdvin** [SquidDev-CC/CC-Tweaked#1525]
So, this is a slight follow-up to #1093 and #899.

The current generic peripheral holds two major problems for add-on development:
1. There is no good way to attach `inventory` or `fluid_storage` peripherals to peripherals that the add-on built. This leads to issues like [this](https://github.com/SirEndii/AdvancedPeripherals/issues/455): with the introduction of new functionality, old functionality is lost. There is only one way to solve this: the modder can copy or re-implement all generic peripherals by himself (this is kind of what UPW [does](https://github.com/SirEdvin/Peripheralium/blob/1.20/projects/core/src/main/kotlin/site/siredvin/peripheralium/extra/plugins/AbstractInventoryPlugin.kt)), but aside from the fact that CC:T generic peripherals often tested better, understanding the source of the issue with chest peripherals or something else quickly becomes a tricky problem.
2. `inventory` generic peripheral, as well as others that attach to Forge/Fabric specific logic, are not extendable. So, there is no way to provide some new cases when StorageWrapper for specific peripheral can be built. This may sound unnecessary because implementation of Fabric/Forge storage logic is often required, but in a lot of cases, such as [storage mod integrations](https://docs.siredvin.site/UnlimitedPeripheralWorks/integrations/ae2/) or [specific use cases](https://docs.siredvin.site/UnlimitedPeripheralWorks/minecraft/powered_rail/) built around entities, providing fabric/forge logic for storage just breaks the internal logic of the mod or Minecraft for the player. 

To solve this, I can suggest the next plan to solve these two issues:
1. Introducing an API for "plugins"[^2] (or whatever name suits better), basically a more extended version of `IDynamicPeripheral`, that can accept "plugins" and then expose their methods as their own[^1]. This will also help add-on developers build their functionality in a more flexible way if this becomes an official API.
2. Create multi-loader item/fluid/energy storage interfaces[^3], which can be implemented anyhow, and "plugins" for `inventory`, `fluid_storage` and `energy_storage` around them. This is probably the weakest point of this plan because CC:T isn't generally built for it.
3. Introduce APIs for building plugins for any storage that implements interfaces and also to wrap fabric/forge plugin to interfaces. So CC:T will not expose implementation directly, but rather an ability to just get plugins for your storage.
4. Add the ability to create storage extraction logic when the default is not catching up.

I can try to implement some steps myself, but I would like to discuss the implementation first before starting to write the code.

There is also a possibility for this to be implemented in some kind of official CC:T modding toolkit rather than the CC:T repository, but I am not sure if this idea is bad or good.

[^1]: There is a reference implementation of this in [Peripheralium](https://github.com/SirEdvin/Peripheralium/blob/1.20/projects/core/src/main/kotlin/site/siredvin/peripheralium/computercraft/peripheral/PluggablePeripheral.kt), which I use, but it is not good enough, I suppose. 
[^2]: I am not sure if the "plugin" term is suitable here, so if anyone has something better, I will rename it.
[^3]: There is also a reference implementation of this in [Peripheralium](https://github.com/SirEdvin/Peripheralium/tree/1.20/projects/core/src/main/kotlin/site/siredvin/peripheralium/storages) which I love and hate at the same time, especially the problem with fabric transaction handling.

**Comment by SirEdvin** [comment]
So ... can I ask for any thoughts about this? :)

**Comment by SquidDev** [comment]
Heads up: this is going to be a ramble, and not really address all of these points in any sensible way:

When the generic peripheral system [was first implemented](https://github.com/cc-tweaked/CC-Tweaked/issues/452), I made a conscious choice to keep the API as small as possible. Plethora's API (and internals!) were incredibly complex, and I wanted to avoid that as much as possible. I'm definitely open to changing/fleshing it out (it really was meant to be the simplest thing, and surprised it's lasted this long), but fear a lot of what you're proposing reaches Plethora-level complexity.

Not 100% related, but it's probably worth mentioning https://github.com/dan200/ComputerCraft/issues/153 and https://github.com/cc-tweaked/CC-Tweaked/issues/633 here. They do somewhat influence the current design of generic peripherals, and solving them would probably simplify some things, I've just never been sure about whether they're actually a good idea.

One of the main aims of the generic peripheral system is that it's an inversion of the normal peripheral provider system. Rather than defining a peripheral for a block and providing all the methods for it, you're effectively mixing-in methods onto a specific type[^1].

[^1]: Fun facts, this system actually works anywhere - it's possible to use a `GenericSource` to add methods to any peripheral or Lua object.

This works pretty well when you stay in generic-peripheral land, as it allows multiple mods to inject methods onto the same block[^2]. However, if a mod wants/needs a dedicated `IPeripheral` it does all fall apart.

[^2]: Though the [lack of priorities](https://github.com/cc-tweaked/CC-Tweaked/discussions/839) is a pain. Again, closely related to the multi-peripheral issue.

I find it really hard to know what to do with this issue, because there's two types of problem here, and I'm not sure how to disentangle them:

 - Issues encountered due to the fact that Peripheralium reinvents the generic peripheral system: For instance, [the create tanks integration](https://github.com/SirEndii/AdvancedPeripherals/issues/455), is a perfect example of what `GenericPeripheral` was designed for!
 - Issues with the generic peripheral system that required Peripheralium reinventing it.

I do think it'd be interesting (though a lot of work, and I know you're busy working on other things!) to see what could be ported over to use `GenericPeripheral`, and where you start hitting issues. I suspect #839 and #899 are the main problems, but don't know for sure.

**Comment by SquidDev** [comment]
There have been some changes to generic methods in the last few months, and would be interesting to see if this helps in any way:

 - Support for custom "lookup" functions (0ff58cdc3e85ef69bbb3a436a1335b5a882d71c3), rather than hard coding our list of `ItemStorage`. This isn't part of the public API (at least yet), but I don't think that matters for you :p.

 - Support for instance methods (fe826f5c9c8098219001c87a8422994263b61ee3, 84a799d27a382f262b5e74edc1fa7c369904de35). Relatively minor, but should make at least make it easier to write generic methods in Kotlin.
