### ISSUE TITLE
Enchanted tools support

### ISSUE THREAD

**Issue by filippocrocchini** [SquidDev-CC/CC-Tweaked#1600]
I would like to be able to use an enchanted pick with fortune 3 and whatever other enchantments make sense.

I have been playing a survival world in adventure mode, using turtles to mine and build. I have to say, the mod works really well in this scenario, I suggest trying it out, however it really falls short when it comes to enchanted tools.
I poked around the repository and saw that you are disallowing enchanted tools because of how you handle items internally so, I realize I'm suggesting a tough feature to implement.

**Comment by SquidDev** [comment]
This is actually possible since 1.106 - it's not enabled by default, but you can override the existing tools via a datapack to add it.

The easiest way to do this is create a new datapack with a `data/minecraft/computercraft/turtle_upgrades/diamond_pickaxe.json` file with the following contents:

```json
{
  "type": "computercraft:tool",
  "item": "minecraft:diamond_pickaxe",
  "allowEnchantments": true
}
```

There's also a [netherite tools](https://github.com/cc-tweaked/netherite-tools/blob/main/make.py) datapack, which adds enchantable turtle upgrades for all netherite tools. Might be a useful reference, even if not quite what you want :).
