### ISSUE TITLE
Monitor rendering issue with shaders

### ISSUE THREAD

**Issue by Xtraaaaaa** [SquidDev-CC/CC-Tweaked#1603]
### Minecraft Version

1.19.x

### Version

1.101.3

### Details

I am having an issue with the monitors using shaders with OptiFine 1.19.2 HD U I2

I have tried BEST, TBO and VBO rendering settings but none of them have worked.

The shaders I am using are [ComplementaryReimagined r5.0.1](https://www.complementary.dev/shaders/)

![image](https://github.com/cc-tweaked/CC-Tweaked/assets/90585446/9d2397e6-a8c2-47a4-b23f-948c9ac70f71)

**Comment by Lupus590** [comment]
Optifine doesn't play well with other mods, the shader mod that usually gets recommended is [Occulus](https://modrinth.com/mod/oculus).

**Comment by SquidDev** [comment]
My graphics driver crashes when trying to use these shaders, so tagging this as a very literal "cannot reproduce".

I did manage to get [MakeUp UltraFast](https://modrinth.com/shader/makeup-ultra-fast-shaders) running, which did work fine with CC's monitors. This suggests this is an issue with Complementary (or possibly a feature of optifine which isn't enabled in all cases).

If you're familiar with this sort of thing, it might be worth poking around with [RenderDoc](https://renderdoc.org/) and seeing what's going on, but I'm afraid I otherwise can't really help.

**Comment by SquidDev** [comment]
Updated my graphics drivers, and no longer get the crash. I'm afraid I still cannot reproduce this, on any of the performance levels.

Just to clarify, you should probably leave the monitor renderer set to VBO or BEST - TBO will definitely not work with shaders :).
