### ISSUE TITLE
256 Color pallete?

### ISSUE THREAD

**Issue by AsrielDewitt** [SquidDev-CC/CC-Tweaked#1634]
- This could breath new life to application developer, access a lot more colors. And also kept with the intention of mimicking an old computer. Old computer like Apple 2 can mimic more colors by just use tricks on monitors.

This isn't possible on CC of course, but upgrading the palette to 256 color palette is a good compromise of staying close to how old retro style computers work while give more wiggle room for colors

**Comment by piprett** [comment]
The limitations are what makes CC amazing

**Comment by SquidDev** [comment]
Thanks for the feature request! I'm afraid I'm not going to implement this - the limited palette depth is an intentional restriction. ComputerCraft borrows a lot from the aesthetic of retro-computers (specifically the BBC Micro), and so intentionally limits its colour choice.

See also the discussion in #1363.
