### ISSUE TITLE
Be able to use composters

### ISSUE THREAD

**Issue by Sebbito** [SquidDev-CC/CC-Tweaked#1638]
I've read through the issues and this one also seems like it's related to the `turtle.use()` request. I'll explain it regardless.

I'm making a farm bot which can already do the farming.
I get a lot of leftover wheat seeds though and i wanted to compost them since it gets rid of the seeds and also gives me bone meal to speed up the plant growth.

I tried `turtle.place()`, `turtle.dig()` and `turtle.drop()` for putting seeds into the composter and/or getting the bone meal out of it. None of these functions worked.

I saw a lot of talk about other mods like Advanced Peripherals, Plethora, etc. filling the gaps but I still couldn't use the composter.
The composter wasn't recognized as a peripheral either using these mods so it seems like a dead end.

Any more tips/tricks or is this just how it be?

**Comment by SquidDev** [comment]
Thanks for the report! Yeah, it sounds like composter should be on our list of blocks we allow placing into - will add it.

For the time being, `turtle.drop()` won't work, as you can't insert into composter from the side. However, putting the turtle above the compostor and doing `turtle.dropDown()` should work (and similarly putting it below and doing `turtle.suckUp()` to extract).

> I saw a lot of talk about other mods like Advanced Peripherals, Plethora, etc. filling the gaps but I still couldn't use the composter.

Yeah, composter are a bit weird, as they're inventories, but _not_ a block entity. I'm hoping this will be a little better on 1.21.0, due to a couple of upcoming changes in the modding APIs.

**Comment by Sebbito** [comment]
Oh my, thank you for the quick reply!!!

> For the time being, turtle.drop() won't work, as you can't insert into compostors from the side. However, putting the turtle above the compostor and doing turtle.dropDown() should work (and similarly putting it below and doing turtle.suckUp() to extract).

Yes that works. Thank you so much and also thank you for all the work you put in this project. It is a load of fun ^^
