### ISSUE TITLE
1.109 update Broke the display colors on the monitor

### ISSUE THREAD

**Issue by laurad2423** [SquidDev-CC/CC-Tweaked#1640]
### Minecraft Version

1.20.x

### Version

1.109.0

### Details

I have been using a public script to handle MineColonies with CC:tweaked and the latest update to 1.109 seems to have broken colors and I have NO idea why. 
Here is the code I am using:
   https://pastebin.com/m84RCE6k
   
 Regular code seems to work to change the color, but the color variables in the code no longer work. Just defaults to the last set color.

**Comment by SquidDev** [comment]
This is caused by your use of `arg` in `mPrintRowJustified` and `mPrintScrollable`. This was deprecated in Lua 5.1 and removed in Lua 5.2. CC:T 1.109 updates the Lua version to use 5.2, hence why you're seeing this breakage.

You can fix this by adding `local arg = table.pack(...)` on lines 84 and 106, before they're used in those two functions.
