### ISSUE TITLE
pcall doesnt stop the script from crashing

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [SquidDev-CC/CC-Tweaked#1650]
### Minecraft Version

1.20.x

### Version

1.108.4

### Details

last time i used cc, calling functions this way stopped scripts from crashing and now it doesn't and according to everything i've read about cc tweaked this should still do the job.

local ok = pcall(term.write())
if ok then
  --work.
else
  --be silent!
end

**Comment by fatboychummy** [comment]
This is not a bug. `pcall` expects the function object, not for you to call the function. What you're doing currently is calling the function, then passing the return value to `pcall`.

What you want is the following:
```lua
local ok, error_message = pcall(term.write)
```

Notice the lack of `()` after `term.write`. This is because we want to pass the function as a variable, not call the function.

If you want to add arguments,
```lua
local ok, error_message = pcall(term.write, "Hello world!")
```

**Comment by C4PTRAMPAGE** [comment]
right so its just one of tweak's many unnecessary changes, because i remember that used to work exactly as i wrote it in cc.

**Comment by fatboychummy** [comment]
> right so its just one of tweak's many unnecessary changes

No, this is a base Lua thing. CC:T tries to stay as true to Lua as possible and this behavior has never changed.
