### ISSUE TITLE
Computer freezes when more than 257 parallel peripheral functions

### ISSUE THREAD

**Issue by Kicory** [SquidDev-CC/CC-Tweaked#1659]
### Minecraft Version

1.20.x

### Version

1.109.2

### Details

Setting: 
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/42833717/85e5d946-c616-4ea7-81aa-a4eca9b5305d)

Lua script wrote:
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/42833717/f0a2200e-dc6c-4ba3-ac13-07ecab41a93a)

Modloader: Neoforge 47.1.83
Other mods: None

If the parallel jobs are 257 or smaller, then everything is OK. The freezing bug only happens when it's 258 or larger. And this bug happens after some trial from computer boot; for first few (mostly less than 2) executions, this bug does not happen.

I tested other lua computation like lua table manipulation or lots of printings, but only functions that interacts with peripherals seemed to be cause problem.

For example, following script also cause the bug.
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/42833717/44d781dc-0c5e-49ca-8090-7c2e145083de)

**Comment by notforsaleyo** [comment]
Oh I forgot to mention; there are no log appears when freezing bug occurs.

**Comment by SirEdvin** [comment]
Since parallel works via events, my guess would be that you probably hit event queue limit

**Comment by notforsaleyo** [comment]
> Since parallel works via events, my guess would be that you probably hit event queue limit

Oh... Then can this problem be bypassed if I use coroutine API directly?

btw thank you for quick answer. this bug was real headache for me...

**Comment by SquidDev** [comment]
I'm afraid this is an intentional design choice. We need a limit for the event queue to avoid entirely unbounded growth, and 256 is a relatively reasonable limit. Most code doesn't really benefit from this level of parallelism, as we rate-limit the work main-thread tasks can do anyway.

If you're trying to scan multiple inventories at once, my recommendation is to instead spin up a smaller number of workers (e.g. 64) and have a shared queue that each worker pulls from. I have some code for this [in one of my projects](https://github.com/SquidDev-CC/artist/blob/ae917778b1feb5f69cb0ee9d6ea3499d71f871ca/src/artist/lib/concurrent.lua#L33-L117), which you're free to use, though it may be over-complicated for your needs.

**Comment by notforsaleyo** [comment]
Thank you, I will take a look.

Actually I already implemented small, easy workaround for my project. This issue is for others who looking for the reason of freezing in the future...

So maybe it would be better to show simple warning message by os, if event queue is full and might cause potential bug.

Thank you for addressing my headache.
