### ISSUE TITLE
Parity between forge and fabric to use an addon cross modloader

### ISSUE THREAD

**Issue by coco875** [SquidDev-CC/CC-Tweaked#1664]
### Minecraft Version

1.20.x

### Version

1.109.2

### Details

because forge version of ComputerCraft initialise later when using with connector he make crash when using with Plethora who are a fabric addon for ComputerCraft (https://mclo.gs/LcdEOCU)
(the line in question is 41: Caused by: java.lang.IllegalStateException: ComputerCraft has not initialised yet?)

**Comment by SquidDev** [comment]
Coping some additional information from IRC: 

> Hello, there is an issue with cc: tweaked and Sinytra Connector. This mod allow fabric mod to run on forge and it seam like the API of cc: teawked forge isn't the same as the fabric one. Because of this fabric add-on cannot be loaded on forge. People on the Sinytra discord server told me to tell you about this, they say it's always a good thing to have parity and it's a good thing to fix.

**Comment by SquidDev** [comment]
I don't think this is due to a mismatch in the API, and more differences between Force and Fabric. On Fabric, registries are created immediately (which Plethora relies on), but on Forge their creation is deferred. Plethora isn't expecting this, and we get this crash.

I don't really think this is something CC:T can fix - we're just using the standard Forge/Fabric APIs here.

**Comment by SquidDev** [comment]
I will also mention that even ignoring this bug, I don't believe Plethora will work on Connector. It relies on several Fabric-specific CC internals.

**Comment by coco875** [comment]
ok thanks to give all the reason
