### ISSUE TITLE
Server crash on connect

### ISSUE THREAD

**Issue by Taigacraft34** [SquidDev-CC/CC-Tweaked#1680]
### Minecraft Version

1.19.x

### Version

1.19.3-forge-1.103.1

### Details

When i try to join my server (Arclight 1.0.2) the server crash

the server was working correctly and without touching any computer the server crashed

Logs https://pastebin.com/rm1t4Paa

Crash-report https://pastebin.com/dVjhWGzy

List of mods i have:
architectury-7.1.70-forge.jar
car-1.19.3-1.0.3.jar
cc-tweaked-1.19.3-forge-1.103.1.jar
cfm-7.0.0-pre35-1.19.3.jar
geckolib-forge-1.19.3-4.0.6.jar
Joban-Client-Mod-1.19.3-1.2.1-hotfix-1.jar
mcw-furniture-3.1.0-mc1.19.3forge.jar
MTR-forge-1.19.3-3.2.2-hotfix-1.jar
MTR-NTE-0.4.1+1.19.3.jar
plasmovoice-forge-1.19.3-1.2.19.jar
worldedit-mod-7.2.13.jar

**Comment by SquidDev** [comment]
Thanks for the report! 

This appears to be the same underlying issue as #979. There's an annoying interaction between Forge's class-loading code and CC:T, where Forge will refuse to load classes once a computer times out.

This has been fixed on Minecraft 1.20.1. The fix was on Forge's end, so I'm afraid it's not something I can feasibly backport. If you're able to update, I'd really I'd really recommend doing so!
