### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/CC-Tweaked#1693]
With the removal of text mode, the fs documentation was updated to reflect the change, however the http documentation still mentions that it takes the `binary` argument, without a deprecation warning or anything.

**Comment by SquidDev** [comment]
Thanks for the report!

I believe the current documentation is correct, though the difference is rather subtle. Both `fs.open` and `http.request` still [support a binary mode](https://tweaked.cc/module/fs.html#v:open). However, this doesn't change the encoding of the file or HTTP request, but rather changes `.read` and `.write` to use single bytes rather than strings.
