### ISSUE TITLE
Turtle - need_fuel doesn't work.

### ISSUE THREAD

**Issue by VenerableTimeWanderer** [SquidDev-CC/CC-Tweaked#1701]
### Minecraft Version

1.20.x

### Version

1.109.3

### Details

All the Mods 9 - The need_fuel doesn't work in the config.

**Comment by SquidDev** [comment]
Thanks for the report! I'm afraid I'm unable to reproduce this at all - I've tried setting `need_fuel` to true and false, and everything works as expected.

Would you be able to clarify what exactly you changed, and what you tested?

Just a couple of things it's worth making sure:
 - Double check you're editing the file in `$WORLD_DIR/serverconfig/computercraft-server.toml` (rather than the one in `configs/` or `defaultconfigs/`).
 - Make sure you've closed the world (or stopped the server if on multiplayer) before editing the config. Forge sometimes likes to overwrite changes in the config.

**Comment by VenerableTimeWanderer** [comment]
Wow yep that works. Thanks learned something new.
