### ISSUE TITLE
Crash on start of game

### ISSUE THREAD

**Issue by PepperMarioYT** [SquidDev-CC/CC-Tweaked#1713]
### Minecraft Version

1.20.x

### Version

1.109.5

### Details

The game crashed whilst initializing game
[crash-2024-02-04_15.18.19-client.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14158396/crash-2024-02-04_15.18.19-client.txt)

Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'computercraft'!
[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/14158381/latest.log)
use the version in bug report (alpha for 1.20.4)
[crash-2024-02-04_15.18.19-client.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14158396/crash-2024-02-04_15.18.19-client.txt)

**Comment by SquidDev** [comment]
Thanks for the report! From the logs, it looks like this might actually be caused by immersive portals - can you try removing that and trying again?

Not relevant to your crash, but as a warning - monitors will be broken when using Immersive Portals (https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1042).

**Comment by PepperMarioYT** [comment]
worked! thx
