### ISSUE TITLE
Cant craft the basic computre or anything with glass panes

### ISSUE THREAD

**Issue by xinsomniax** [SquidDev-CC/CC-Tweaked#1725]
### Minecraft Version

1.19.x

### Version

1.101.4

### Details

Just says forge:glass_panes but doesnt allow for crafting with any glass panes

**Comment by SquidDev** [comment]
Thanks for the report! This sounds like a bug with your modpack (or a datapack you're using) rather than an issue specifically with CC:T. 

It might be worth reporting this on your modpack's issue tracker, if they have one. Otherwise, would you be able to upload your logs, and I might be able to have a look.
