### ISSUE TITLE
Invalid color check fails.

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/CC-Tweaked#1736]
### Minecraft Version

1.20.x

### Version

1.109.6

### Details

This was found by a different person in the discord guild.
When trying to set the background/text color to something invalid, like 100, advanced computers error as they should.
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/78849100/9a5cbc16-24ea-4bd2-84e4-b5b916046879)
However, this is not the case with basic computers and monitors.
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/78849100/78fc2924-ed96-4cff-8695-f2f5dd761c3a)
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/78849100/55b64034-d7b6-4017-b010-14ce7b318ccb)
(The monitor color does change)
I assume this is the case because multishell checks if the color is valid, but the native terminal errors silently.

**Comment by SquidDev** [comment]
So there's a mismatch here between what the various `term` implementations do:

 - The native (Java) terminal, [uses the highest bit to find the colour][parseColour] (this is also what [`color.toBlit`][color.toBlit] does).
 - Meanwhile the `window` API [just uses a lookup table on the "correct" colours][window].

The `term.Redirect` contract is a little underspecified here in terms of what values are supported. I think we probably need to make the following changes:

 - `window` should use `color.toBlit` (or probably an inlined version, to minimise the performance cost).
 - `color.toBlit` should perform bounds checks - `color.toBlit(2 ^ 16)` will currently return `"10"`, when it should error.
 - Update the `term.Redirect` documentation to specify the expected behaviour:
    - Callers of `set.*Colou?r` functions should only pass in valid colours.
    - Implementations *may* accept invalid colours, following the conversion logic in `colors.toBlit`.

[parseColour]: https://github.com/cc-tweaked/CC-Tweaked/blob/4daa2a2b6a839769c8be31425780e6c75c1bd752/projects/core/src/main/java/dan200/computercraft/core/apis/TermMethods.java#L335-L340
[color.toBlit]: https://github.com/cc-tweaked/CC-Tweaked/blob/4daa2a2b6a839769c8be31425780e6c75c1bd752/projects/core/src/main/resources/data/computercraft/lua/rom/apis/colors.lua#L368-L371
[window]: https://github.com/cc-tweaked/CC-Tweaked/blob/4daa2a2b6a839769c8be31425780e6c75c1bd752/projects/core/src/main/resources/data/computercraft/lua/rom/apis/window.lua#L400-L402
