### ISSUE TITLE
Jade reports Wired modems as Networking Cable

### ISSUE THREAD

**Issue by wolfieboy09** [SquidDev-CC/CC-Tweaked#1762]
### Minecraft Version

1.20.x

### Version

1.110.1

### Details

![image](https://github.com/cc-tweaked/CC-Tweaked/assets/105564186/8dadf9f2-ae3f-40d0-9ed9-5b80be0b4a30)
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/105564186/16465bcd-da6f-47cb-b3ef-4e45b44576c3)
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/105564186/1be3e2c8-7330-49af-806b-3a7639d0bd85)

Latest log:
[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/14735777/latest.log)

**Comment by SquidDev** [comment]
Minecraft only supports having a single name for a block, which doesn't play well with the multipart-like wired modem. It is possible to fix this via the WAILA/Jade API, but it doesn't feel worth it for a relatively minor cosmetic issue.


Please remember when reporting bugs, that you're trying to make the life of mod developer as easy as possible! Try to include as much information as possible - for instance, it would have been really useful to know that the WAILA-like mod here was Jade, rather than having to guess from your logs!

**Comment by wolfieboy09** [comment]
Quick question, whats "WAILA"?

**Comment by piprett** [comment]
What Am I Looking At. A minecraft mod that does the same as Jade (displaying what something is).
