### ISSUE TITLE
infinite water sources on network cables don't work

### ISSUE THREAD

**Issue by Plite7067** [SquidDev-CC/CC-Tweaked#1766]
### Minecraft Version

1.20.x

### Version

1.110.1

### Details

I believe this is because of the most recent update, as its changelog mentions overhauling network cables.
![1711483715-wayshot](https://github.com/cc-tweaked/CC-Tweaked/assets/121261510/0de0d3eb-1d7b-4349-b3f4-6d915337cf03)
![1711483735-wayshot](https://github.com/cc-tweaked/CC-Tweaked/assets/121261510/663c41d4-0aec-4db9-8b75-c69ded7532fe)
![1711483739-wayshot](https://github.com/cc-tweaked/CC-Tweaked/assets/121261510/e4d9ff9b-cbc9-4827-ae10-14f81449cca2)
This breaks my build. Please ask if you need any more information.

**Comment by SquidDev** [comment]
Thanks for the report! I'm afraid I cannot reproduce this at all I have tried both a basic 1x3 setup, and the deeper configuration in your screenshot - in both cases, they form water source blocks.

Would you be able to include the following:

 - Logs: These will be located in the `logs/` directory of your Minecraft instance.
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed.

**Comment by Plite7067** [comment]
Interesting - it could be because I updated from 1.19?
[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/14772119/latest.log)
I'll try on a new world. The reproduction steps were just creating any infinite water source above network cables, then using any method to remove a water source block and it not regenerating.

**Comment by Plite7067** [comment]
it still happens in a new world. I will try with just cctweaked in a new instance

**Comment by Plite7067** [comment]
In a new instance, with a different launcher, with minecraft version 1.20.1, forge version 47.2.17, and cctweaked 1.110.1, from modrinth, and only cctweaked in the mods folder, it still happens. (last time i used neoforge). Here is a video:

https://github.com/cc-tweaked/CC-Tweaked/assets/121261510/5e18a057-4322-4c9f-94bb-aeb15e83d45e

**Comment by SquidDev** [comment]
Ahhh, this occurs when the cables below the water are *not* waterlogged.

The issue here is that water only spreads on top of solid blocks (or other water sources). Unfortunately, Minecraft's definition of what is and isn't solid is a little ... bizarre. For instance, only the cable in the middle here counts as solid:

![A 3x3 square of network cables. Each cable is connected to its neighbours, with the very centre cable being connected on four sides.](https://github.com/cc-tweaked/CC-Tweaked/assets/4346137/ae7117cc-9fc4-4936-85fe-ef7cc73604b3)

We can force the cable to be counted as solid, but not sure if that has any unexpected repercussions elsewhere in the game - will need to go through and check.

For now, would just recommend you waterlog the cables too.

**Comment by Wojbie** [comment]
> Interesting - it could be because I updated from 1.19? [latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/14772119/latest.log) I'll try on a new world. The reproduction steps were just creating any infinite water source above network cables, then using any method to remove a water source block and it not regenerating.

![obraz](https://github.com/cc-tweaked/CC-Tweaked/assets/5893536/69d6e47e-a97f-48dc-921f-b7aaad19f146)

Based on this message i was able to replicate this - if cable is waterlogged then source block forms correctly. But if you don't waterlog it then it is not considered valid shape for generating water? So it works correctly.

EDIT: And got ninjaed by Squid itself.

**Comment by Plite7067** [comment]
Nice - thanks. I was just confused, as it worked in 1.19
