### ISSUE TITLE
/computercraft give

### ISSUE THREAD

**Issue by tizu69** [SquidDev-CC/CC-Tweaked#1864]
A command that gives the user a computer with a specificed ID and type.

`/computercraft give <id> [type ?? computercraft:computer_normal]`
ID is the computer ID, not instance ID.

While this is possible without a command like this, it's a pain to remember how to.

**Comment by zyxkad** [comment]
why do you want a specific ID?

**Comment by fatboychummy** [comment]
> why do you want a specific ID?

Mainly for creative worlds. 

Started programming on an advanced computer but now want to work with commands? Give yourself a command computer with the same id, instead of copying/moving all the files to a new id. Want to see if your ui scales well on a turtle's smaller screen? `/give` yourself a turtle with the same id.

**Comment by SquidDev** [comment]
CCTweaks had this [way, way back](https://github.com/SquidDev-CC/CCTweaks/wiki/CCTweaks-command#give-item-id-label-family), which was useful (as computers stored their IDs in metadata).

However, in modern versions of the game, all computers store IDs in the same way, so I don't actually think it's too annoying (either to do, or to remember);

 - Minecraft 1.20.1: `/give @p computercraft:computer_normal {ComputerId:123}`
 - Minecraft 1.20.5+: `/give @p computercraft:computer_normal[computercraft:computer_id=123]`

Also worth noting that 1.20.5 and later also give you auto-complete, so even easier to remember!
