### ISSUE TITLE
Flux Gate not Working with CC:Tweaked Wired Modum when attached to Reactor Energy Injector

### ISSUE THREAD

**Issue by clb158** [SquidDev-CC/CC-Tweaked#1897]
### Minecraft Version

1.20.1

### Version

1.20.1

### Details

Minecraft version: 1.20.1
Minecraft Forge version: 47.2.20
Mod Pack: All the Mods 9 - To the Sky

Description / steps to reproduce
Connect Wired Modem to Flux Gate Connected to Reactor Energy Injector and find zero interaction with Modem.
![image_2024-07-07_012243412](https://github.com/cc-tweaked/CC-Tweaked/assets/93491190/3f29c29b-7028-482d-b8b0-e88b9e41cfe6)

**Comment by fatboychummy** [comment]
Did you right-click the modem after you placed it? If it's supported, it should say in chat "peripheral 'xyz' connected to network" in chat, and the center will turn red. But only after you right-click it again.

**Comment by zyxkad** [comment]
Note that wired modem on cable does not always works, you may want to try full wired modem instead

**Comment by fatboychummy** [comment]
> Note that wired modem on cable does not always works, you may want to try full wired modem instead

This is the case *if* the block does not have any "full sides" that allow placement, like chests and the like. If it allows you to place the modem on the block, it should work.

**Comment by clb158** [comment]
> Did you right-click the modem after you placed it? If it's supported, it should say in chat "peripheral 'xyz' connected to network" in chat, and the center will turn red. But only after you right-click it again.

yes i did and there is no interaction

**Comment by zyxkad** [comment]
> > Did you right-click the modem after you placed it? If it's supported, it should say in chat "peripheral 'xyz' connected to network" in chat, and the center will turn red. But only after you right-click it again.
> 
> yes i did and there is no interaction

Then probably flux gate is not a peripheral block, you can report to their github repo

**Comment by clb158** [comment]
> > > Did you right-click the modem after you placed it? If it's supported, it should say in chat "peripheral 'xyz' connected to network" in chat, and the center will turn red. But only after you right-click it again.
> > 
> > 
> > yes i did and there is no interaction
> 
> Then probably flux gate is not a peripheral block, you can report to their github repo

yeah i did they said "in the works" lol

**Comment by zyxkad** [comment]
Ok, well, alright, then there is nothing CC:T can deal with it except tell you it's not a peripheral block when right clicking

**Comment by SquidDev** [comment]
Thanks for the report! I'm afraid this appears to be an issue on the Draconic Evolution side, and there's not much on CC:T's side I can do to fix it.

As you've already mentioned, [Draconic Evolution's peripherals aren't currently implemented](https://github.com/Draconic-Inc/Draconic-Evolution/blob/c5978cf46f88a4c287af458d182bd683e2774386/src/main/java/com/brandon3055/draconicevolution/integration/computers/PeripheralFlowGate.java#L72-L76).

CC:T *should* fall-back to it's more generic [`energy_storage`](https://tweaked.cc/generic_peripheral/energy_storage.html) implementation. However, because the flux gate only supports energy I/O on its front and back (and DE doesn't correctly support the `null` side), this doesn't work. You get a peripheral if you attach a modem to the back of the flux gate, but obviously that then means you can't insert energy into it!

**Comment by SquidDev** [comment]
Have submitted a PR to DE that should hopefully resolve this issue: https://github.com/Draconic-Inc/Draconic-Evolution/pull/1817.
