### ISSUE TITLE
Wrong JSON serialization

### ISSUE THREAD

**Issue by Zelaux** [SquidDev-CC/CC-Tweaked#1920]
### Minecraft Version

1.19.2

### Version

v1.102.2

### Details

![изображение](https://github.com/user-attachments/assets/0c695561-0b15-4511-8e88-f1bf359037c9)
Code to reproduce
```lua
local value = 0
local pack1 = table.pack(value)
local pack2 = table.pack(pack1, nil)
print("serialise", textutils.serialise(pack2))
print("serialiseJson", textutils.serialiseJSON(pack2))

print("Click to exit")
os.pullEvent("mouse_click")
```

**Comment by Zelaux** [comment]
https://tweaked.cc/module/textutils.html#v:serializeJSON
- Throws
   If the object contains a <b>value which cannot be serialised</b>. This includes functions and tables which appear multiple times.

**Comment by SquidDev** [comment]
Oh, this is a bit of a nasty one. As the docs state, this function attempts to guess whether a table is a JSON array or object — if all keys are numeric, then this is treated as an array, otherwise it's assumed to be an object.

In this case, because there's an `n` key, we assume it's an object. I think this is probably the right behaviour (otherwise you get all sorts of ambiguities with `{ n = 0 }`), but definitely a little annoying.

I don't think we can really change the implementation of the function here without breaking existing users, so best thing is probably to clarify the docs to explain the rules here and mention the caveats.

**Comment by Zelaux** [comment]
You can add an error, to indicate that's object cannot be fully serialized
