### ISSUE TITLE
Mod Error

### ISSUE THREAD

**Issue by Kratok21** [SquidDev-CC/CC-Tweaked#1929]
### Minecraft Version

1.20.1

### Version

1.112.0

### Details

Everytime I get into the game, this mod gives me a specific error.
[crash-2024-08-08_13.13.46-fml.txt](https://github.com/user-attachments/files/16541631/crash-2024-08-08_13.13.46-fml.txt)
[latest.log](https://github.com/user-attachments/files/16541636/latest.log)
![CCError](https://github.com/user-attachments/assets/52348f76-2fdf-4243-94ae-5e8d83fb6486)

**Comment by SquidDev** [comment]
Thanks for the report! This appears to be an issue with the VS Addition mod. They're mixing in to some code that has changed in the latest version, so that will need updating.

This bug appears to have been reported already (https://github.com/xiewuzhiying/VS-Addition/issues/19, https://github.com/xiewuzhiying/VS-Addition/issues/23), but not sure if the fix has been released yet.
