### ISSUE TITLE
Crash on mining Stella Arcanum (again)

### ISSUE THREAD

**Issue by gitlias** [SquidDev-CC/CC-Tweaked#1936]
### Minecraft Version

1.20.1

### Version

1.111.0

### Related Issues
#667, #585, #301, #600

###Log
[crash-2024-08-14_18.44.56-server.txt](https://github.com/user-attachments/files/16617852/crash-2024-08-14_18.44.56-server.txt)

###Reproduction Steps

1. Have Mining Turtle mine Stella Arcanum
2. Stella Arcanum should Explode
3. Doesn't (It does not seem to relate to the Turtle turning as in #667)
5. Tick takes over 60s
6. Server says Bye

I could also reproduce this in singleplayer.

**Comment by SquidDev** [comment]
Thanks for the report! I'm afraid I can't reproduce this with just CC:T and Forbidden Arcanus. I suspect this is caused by another mod doing some funky mixin, but it's not immediately obvious looking at the crash who that is.

Do you have a link to the modpack you're using?

**Comment by gitlias** [comment]
@SquidDev I'm playing Valhelsia 6 https://www.curseforge.com/minecraft/modpacks/valhelsia-6

**Comment by gitlias** [comment]
I went through the other crash logs and noticed a third mod showing up in the possible suspects list. That being Polymorph.
[crash-2024-08-14_18.33.57-server.txt](https://github.com/user-attachments/files/16619618/crash-2024-08-14_18.33.57-server.txt)

**Comment by SquidDev** [comment]
I'm afraid I can't reproduce, even in the full pack. I'm currently running version 6.2.2, and did the following:

 - Place down a mining turtle.
 - Place down stella arcanum in front of the turtle.
 - Open the turtle, insert some items into the first slot.
 - Run `lua` and then `turtle.dig()`.
 - The turtle explodes, and drops the items in the first slot and the stella arcanum. The turtle is currently not dropped due to a different bug (bb97c465d963ca325806a81b0de0d41b021af085).

Do you have any additional mods in the pack?

**Comment by gitlias** [comment]
@SquidDev No additional Mods. It still happens on a fresh server install for me. I just tried it again, it happens using the built in excavate and tunel command. Sorry for not including that from the start.

**Comment by SquidDev** [comment]
Hah, that was a nasty one. Thank you for the extra info, that was very useful!
