### ISSUE TITLE
Monitor not refreshing characters properly

### ISSUE THREAD

**Issue by SamsTheNerd** [SquidDev-CC/CC-Tweaked#2013]
### Minecraft Version

1.20.1

### Version

1.114.0

### Details

I'm guessing it's a duplicate of #2010 but posting incase it's not.

Steps to reproduce:
- place computer + monitor
- run `monitor right shell`
- type `c` such that `cd` gets autosuggested
- backspace
- monitor shows `_d` with the `d` flashing.

<img width="966" alt="image" src="https://github.com/user-attachments/assets/1958a8b7-cfd9-4f58-a26b-74b1a27a8b76">

**Comment by SquidDev** [comment]
Thanks for the report! I'm afraid I can't reproduce this, either on the main 1.114 release, or on the latest commit (1d7d8006d4edc6db09e0dda9f3bd537492f9d3e3) (both tested on Fabric).

**Comment by SamsTheNerd** [comment]
hmmmm. tested it on a friend's computer and doesn't happen there either? Weird. He is on linux, I am on MacOS, if it's somehow an OS dependent issue??

**Comment by SquidDev** [comment]
At the risk of asking the obvious, have you tested on a fresh install with just CC:T? Just to double check to other mods are causing issues. 

It might also be worth testing with older versions of the mod, to see if the issue still occurs. 

How often does this bug occur? Is it every time, or intermittent? If you're on Apple Silico, its *posssible* there's some thread-safety issues (ARM has a stricter memory model than x86, and I'm surprised its not caused more issues, but also I don't *think* that's the problem here).

If this is an OSX specific bug, I'm afraid you might have to debug this yourself. A good first step might be to log incoming monitor packets, to see if the latest terminal contents is being sent — it's not clear to me right now if the issue is in the networking or rendering code.

**Comment by SamsTheNerd** [comment]
Yep, fresh install. I first got the bug when I was testing ducky in a dev environment and thought I broke something lol, so tested in a fresh prism env with just cct and fabric. Same setup as my friend I believe.

I'm on an Intel Mac so wouldn't be arm issues. It does occur every time.

It does blink regularly, like a cursor would blink but with the ghost of a text? I can test older versions and record a video of it tomorrow-ish (tried to record a video initially but GitHub didn't want to accept it)

**Comment by SquidDev** [comment]
One thing I did notice in the 1.21.3 update is that the vertex offset we use for the cursor is slightly wrong. Can you try [changing this line to be `+ 4` instead of `+ 6`](https://github.com/cc-tweaked/CC-Tweaked/blob/cddb8fec112abd5c22b377461c3e94c37f4c944a/projects/common/src/client/java/dan200/computercraft/client/render/monitor/MonitorBlockEntityRenderer.java#L213-L214), and see if that helps?

I'm a little surprised that this renders anything (2 verticies isn't enough for anything!), but just to check.
