### ISSUE TITLE
Port to 1.21.3

### ISSUE THREAD

**Issue by TheUserOfReality** [SquidDev-CC/CC-Tweaked#2019]
Port for Minecraft 1.21.3 please?

P.S. I have no experience in Java or mod development for Minecraft. I can't even get the assemblies already builds...

**Comment by SquidDev** [comment]
There is a WIP update to 1.21.3 on the [`1.21.y` branch](https://github.com/cc-tweaked/CC-Tweaked/commits/mc-1.21.y). However, it has several major bugs, so which need fixing before making anything generally available. Given 1.21.4 is less than a week away, I'm afraid I have no plans to release something for 1.21.3.

My general understanding is that the remaining 1.21 versions (so 1.21.3, 1.21.4, and a hypothetical 1.21.5) are likely to be pretty quiet modding wise. Heck, JEI doesn't even have a release for 1.21.3 yet! My plan is to spend this time cleaning up some of CC's internals (see #2008 for some additional info), and do a proper release for MC 1.22.

I'm hoping to get a release together for 1.21.4 in the new year, but no promises. This is all very much time permitting.

**Comment by vico93** [comment]
Chatting with guys of olauncher on their Discord server, i start to think Mojang is moving the kind of cycle we were used to - updates with features at major versions, like 1.21, 1.22... - to minor (third digit) versions (1.21.1, 1.21.2...), specially after the introduction of the concept of [game/feature drops](https://minecraft.wiki/w/Version_types#Game_Drops) - as outlined by [this article](https://www.minecraft.net/en-us/article/the-future-of-minecrafts-development) on Mojang's website.

This sucks for modding, since it looks like they are basically migrating to a rapid developement cycle (when most of every update have breaking changes that require modders to act upon), and honestly i don't know if we will see an 1.22 anytime soon.

**Comment by vico93** [comment]
So, judging by the snapshot cycle, 1.21.5 (some says it will be 1.22 finally, but most of the sources firmly says it will be the first) will again be a breaking minor update, and I'm really afraid if the development speed Mojang is going to will impact future updates to CC:Tweaked.

@SquidDev sorry to ping you, but with these new information, i would like to know what are the plans for the future of the mod.

**Comment by SquidDev** [comment]
The plans remain as they always have — to update when I have time and energy to do so.
