### ISSUE TITLE
Curseforge denying modpacks due to your removing versions

### ISSUE THREAD

**Issue by ModernGamingWorld** [SquidDev-CC/CC-Tweaked#2042]
I understand you are only supporting Modrinth now, but this is causing a lot of headaches for us who still use Curseforge. Any server files that have the following version below in their modpacks can't have their modpacks approved unless they remove your mod from their packs or reach out to Curseforge support to get it approved, and Curseforge takes forever to get ahold of. This is causing issues for people who rely on CurseForge for income and downloads. I have even told them you wont post on CurseForge anymore and that still was not enough to get them to approve the files quicker

Notes:
The following file versions have been removed from CurseForge:
Monumental_Experience/mods/cc-tweaked-1.20.1-forge-1.114.0.jar

The modpack will not be approved until these files are replaced with versions that are currently available.
If you have any questions, please contact our support team at https://support.curseforge.com/.

**Comment by Wojbie** [comment]
Discussed in #2017 
That version was explicitly removed due to significant bug it has.

Edit: can't you use earlier not bugged version? Or is there something in curseforge that is forcing users to use bugged unpublished one?

Because to me it sounds like it's doing things correctly and stop users from using bugged release?
