### ISSUE TITLE
1.13 Crashes with java.lang.NoSuchMethodError during RegistryEvent.Register<minecraft:blocks>

### ISSUE THREAD

**Issue by chorman0773** [SquidDev-CC/CC-Tweaked#206]
- Minecraft Version: 1.13.2
 - CC:Tweaked Version:  1.13.2-1.82.3
 - Detailed reproduction steps: Occured during launch.

During launch with just computercraft and forge, the game crashed with a java.lang.NoSuchMethodError during RegistryEvent.Register<minecraft:blocks>.

The method being invoked, which could not be resolved was `net.minecraft.state.EnumProperty.create(Ljava/lang/String;Ljava/lang/Class;)Lnet/minecraft/state/EnumProperty;`.
This was called from `dan200.computercraft.shared.computer.BlockComputer.<clinit>`, (static initializer) from line 28 of BlockComputer.java.

**Comment by SquidDev** [comment]
I'm unable to reproduce on Forge 25.0.209 and CC:T 1.13.2-1.82.3. Can you make sure you're on the latest version and try again. If it still fails, would it be possible to attach your full logs and crash report?

I've double checked the jar, and it's definitely using the obfuscated name instead of the deobfuscated one, so not even sure how this error is happening. Are you using the CurseForge build, or something else?

**Comment by chorman0773** [comment]
Yeah, I was using the GH Build. I didn’t know about the CurseForge one
