### ISSUE TITLE
read-only floppy disk

### ISSUE THREAD

**Issue by chenxuuu** [SquidDev-CC/CC-Tweaked#254]
can I make a read only floppy disk?
If I create a floppy disk, then copy a same item
when I change files in one disk, it also changed in another disk

how to make a read only floppy disk?

**Comment by JakobDev** [comment]
It is not possible to make a read-only floppy disk.

**Comment by lupus590** [comment]
I seem to remember treasure disks being read-only.

Perhaps this could be a new feature, right-clicking a disk in your hand will convert it to read-only, right-clicking again undoes this.

**Comment by chenxuuu** [comment]
> I seem to remember treasure disks being read-only.
> 
> Perhaps this could be a new feature, right-clicking a disk in your hand will convert it to read-only, right-clicking again undoes this.

add a item like `Compact disc` ?

**Comment by SquidDev** [comment]
> If I create a floppy disk, then copy a same item, when I change files in one disk, it also changed in another disk

The issue here is that copying a floppy disk duplicates the item, but not the files. You've now got two disks which point to the same location (often referred to as "quantally entangled disks"), and so obviously modifying the files on one modifies the other.

Read only floppies would definitely be feasible, but worth thinking about how it'd work first (and the use-cases).
