### ISSUE TITLE
Chests as Peripherals

### ISSUE THREAD

**Issue by shelbykauth** [SquidDev-CC/CC-Tweaked#27]
With the wired modem, I should be able to use a chest as a peripheral, yes?  I can't seem to get it to work properly, and I'm not sure what I'm doing wrong, or if it's actually a bug.  Probably I just can't intuit what to do.

I can right click the full-block modem and it says "Peripheral 'computer_0' connected to the network".  I can open the modem peripheral via lua.  But when I try `p.getNamesRemote()` it gets nothing.  I can't do anything (trying to right-click) with a full-block modem next to just a chest or next to the lit-up modem.

**Comment by SquidDev** [comment]
The wired modem doesn't provide any additional peripherals, it simply allows you to attach modems to blocks which are not solid blocks (turtles, chests). In order to wrap a chest as a peripheral, you'll need a mod which provides such functionality. This can be done with [Plethora](https://squiddev-cc.github.io/plethora/).

I realise the wording isn't very clear - I'll update it to make it a little more obvious.
