### ISSUE TITLE
[1.14.4] Exploit- Turtles dupe when you break them indirectly with a hammer.

### ISSUE THREAD

**Issue by ProsperCraft** [SquidDev-CC/CC-Tweaked#289]
## Useful information to include:
 - Minecraft version forge-1.14.4-28.0.49
 - CC: Tweaked version cc-tweaked-1.14.4-1.84.1
 - place a turtle down and cobble next to it, break the cobble with a hammer, and the one turtle that was broken indirectly now becomes 2 place those two next to a cobble and break that cobble, and those two become four.

**Comment by SquidDev** [comment]
Is the hammer a vanilla item, or a modded one?

**Comment by ProsperCraft** [comment]
Modded hammer from SilentGems, and tested the same with one from Ray's Dongles

**Comment by SquidDev** [comment]
This is a bug with both SilentGear and Ray's dongles - their break handlers include the following code:

```java
state.getBlock().onBlockHarvested(world, pos2, state, player);
tool.getItem().onBlockDestroyed(tool, world, state, pos2, player);
TileEntity tileEntity = world.getTileEntity(pos2);
if (state.removedByPlayer(world, pos2, player, true, state.getFluidState())) {
  // ...
```

However, `removedByPlayer` also calls `onBlockHarvested`, which means it's being called twice.

CC has some slightly weird block-drop code in order to ensure computers are still dropped in creative mode, which is why it only happens to CC:T blocks, but it's still a bug in their code.

**Comment by RayzoRayy** [comment]
@SquidDev Thanks for pointing this out. It has been fixed.

**Comment by SquidDev** [comment]
Fantastic. Thank you for the fast fix!
