### ISSUE TITLE
Add ability to change the tool in tool upgrade crafting recipes

### ISSUE THREAD

**Issue by Trinsdar** [SquidDev-CC/CC-Tweaked#320]
- Minecraft version: 1.12.2
 - CC: Tweaked version: 1.85.2
I an unable to remove turtle tool upgrade recipes. this is my script: https://paste.dimdev.org/atasafirek.cs. here's a gif:
![turtle](https://user-images.githubusercontent.com/30245301/69925419-1e006a80-147e-11ea-9120-47fe00fd5998.gif)

maybe this could be fixed by adding a config for what the tool is?

**Comment by SquidDev** [comment]
Turtle upgrades recipes [are a single dynamic recipe](https://github.com/SquidDev-CC/CC-Tweaked/blob/master/src/main/resources/assets/computercraft/recipes/turtle_upgrade.json), so I wouldn't expect you to be able to disable it using CraftTweaker. Likewise you shouldn't be registering turtle recipes using CT, as they won't behave the same and it'll end up with buggy behaviour.

Just to double check, you're trying to change the mining upgrade to require a thaumcraft pick instead of a diamond one?

As you mention, a config option would be possible, but I wonder if explicit CraftTweaker integration would be a better bet. So you can have some sort of:

```zenscript
turtle.setUpgradeItem("minecraft:diamond_pickaxe", <thaumcraft:elemental_pick>)
```

Alternatively, just provide the ability to remove upgrades and register new ones. This might provide a nice solution to #97 too.

**Comment by Trinsdar** [comment]
Yah, i'm trying to change the upgrade item, so something like that could work

**Comment by Trinsdar** [comment]
Also i'm confused how they would be buggy since i copy over the nbt from the input to the output without any problems that i've been able to see. Just curious; i would still prefer the ct method

**Comment by SquidDev** [comment]
I haven't tested this, but I don't think the above code handles the case when crafting with both a left and right upgrade. Strictly speaking, upgrading should also fail if the _upgrade item_ has any NBT data (such as enchantments), though that's less critical.

It might be possible to write an implementation within CT which accurately mimics the default behaviour, but it's gonna be a lot of pain, and the JEI recipe handlers will still return incorrect results. For better or worse, this is something which I'll have to handle within CC itself.
