### ISSUE TITLE
How do users access APIs and ROM files?

### ISSUE THREAD

**Issue by ejm554** [SquidDev-CC/CC-Tweaked#322]
How can a regular user access, edit, and create APIs and/or the ROM files in CC:T? The (legacy?) CC wiki states the following on the API category page*:

> All the stock APIs of the first kind, those that are implemented in Lua, can be found in your "mods/ComputerCraft/assets/computercraft/lua/rom/apis" directory. 

I cannot see any directory like this in my mod directory unless I convert my CC:T JAR file to a regular folder. However, when I do this, Minecraft won't run, i.e., it appears that the mod has to remain in the JAR format, which then makes it difficult (impossible?) to use.

Is there a way to do this with CC:Tweaked?

FYI, I'm running macOS (v10.11) and Minecraft Forge (v1.12.x-14.23.x). I'm not using a server; my world is based on my hard drive.

*See: http://computercraft.info/wiki/Category:APIs

**Comment by JakobDev** [comment]
You can use a data pack.

**Comment by SquidDev** [comment]
Oh goodness, that documentation is incredibly old (or just wrong - I can't even remember a time when it worked like that). As @JakobDev suggests, the solution is to use a resource pack/data pack instead.

Basically, instead of having a `mods/COmputerCraft` folder, you need to create your own `resourcepacks/whatever` folder. So you'd end up with `resourcepacks/whatever/assets/computercraft/lua/rom/apis`. Then you can add files to there.

There's a [template resource pack and more instructions](http://www.computercraft.info/forums2/index.php?/topic/14049-how-to-make-and-install-lua-resource-packs/) on the CC website, which should still work despite the date!

**Comment by ejm554** [comment]
Okay, I think I get it. Thanks! The info from Dan200 on the CC website was useful, although my Minecraft said in no uncertain terms that the example files were old and not compatible with v1.12.2.
