### ISSUE TITLE
crash by term.blit()

### ISSUE THREAD

**Issue by luochen1990** [SquidDev-CC/CC-Tweaked#379]
## Useful information to include:
 - Minecraft version: 1.15.2
 - CC: Tweaked version: cc-tweaked-1.15.2-1.86.2
 - Detailed reproduction steps: `term.blit("abc", "red", "whi")`

I don't know how to use term.blit(), I have read [the api document](http://www.computercraft.info/wiki/Term_(API)) but there is no details about what the second and third argument should be, so I tried myself, and find that this API will crash the game.

**Comment by Lemmmy** [comment]
The second and third arguments show each character's text and background colour respectively - that's why they have to be the same length as your string. You have to use the colour's hexadecimal code (0-9a-f), which you can find on the new wiki: https://wiki.computercraft.cc/Colours_API

For example, to blit the text "ABC" with red text and a white background, you'd use the code `e` for red and `0` for white:

```lua
term.blit("abc", "eee", "000")
```

The blog function allows you to specify a different colour for each character in an efficient way. For example, to draw rainbow text on a black background:

```lua
term.blit("Rainbow", "e145ba2", "0000000")
````

Notice how every character in the second string is different - these are the text colours and each character corresponds to a different colour code that can be found in the table I linked. Likewise, every character is the same in the third string, because all the characters are on a black background.

**Comment by Lemmmy** [comment]
Also,

> I have read the api document but there is no details about what the second and third argument should be

![](https://user-images.githubusercontent.com/858456/75908402-fd133100-5e41-11ea-98b5-8525c86bbe1d.png)

And there are three examples on there.

**Comment by luochen1990** [comment]
@Lemmmy  Thanks, thats very helpful,  I forget to click inside the detail page...  

But still, I think this is a bug, since improper call of API should not crash the game...

**Comment by Lemmmy** [comment]
Definitely still a bug, yeah. It only crashes with invalid characters in the colour strings (g-z), right? A normal blit usage like `term.blit("a", "0", "f")` works correctly?

**Comment by SquidDev** [comment]
I'm fairly sure this will never crash the game - we catch any errors within computers, so problems should never propagate elsewhere.

As Lem says, if you've still got the crash logs kicking around (or are able to reproduce again), please upload them and I'll reopen this issue!.
