### ISSUE TITLE
Turtle and images?

### ISSUE THREAD

**Issue by Minecraft2p0** [SquidDev-CC/CC-Tweaked#406]
Is it possible to include images or icons in extended Turtles?

**Comment by SquidDev** [comment]
I'm afraid I don't quite know what you mean here. Are you referring to displaying images on the computer screen? Or the fancy decals one could apply with ComputerCraftEdu?

**Comment by Minecraft2p0** [comment]
Thank you for your prompt reply.

I wrote a startup program to access all of my Turtle programs. So far, this has worked using single-color buttons that open menus for me. I would rather have small pictures instead of the single-color buttons.

**Comment by SquidDev** [comment]
So ComputerCraft/CC:Tweaked doesn't have support for 'standard' image formats like PNG and whatever. However, you can do somewhat decent icons if you're comfortable with pixel art. For instance, here's some examples from [Opus OS][opus]

![image](https://user-images.githubusercontent.com/4346137/79634072-35f03680-8160-11ea-84a0-8c0fcf750dae.png)

The easiest way to do that is to use the paint program to draw something, and then [blittle] to shrink it down to something a little smaller - you may lose some detail, due to the limitations of blittle, but it's normally pretty good.

Then you can draw the icon to the screen, and treat it as a button.

[opus]: http://www.computercraft.info/forums2/index.php?/topic/27810-opus-os/
[blittle]: http://www.computercraft.info/forums2/index.php?/topic/25354-cc-176-blittle-api/

**Comment by Minecraft2p0** [comment]
This is fantastic and exactly what I was looking for. Thank you very much and happy programming.
