### ISSUE TITLE
Flame graph performance monitor

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/CC-Tweaked#43]
run `/computercraft perf <id>` and wait a second or two, then `/computercraft perf stop` and it would give you something like these: 
![](https://i.would.download/a-mice.png)

see: https://github.com/brendangregg/FlameGraph

**Comment by Lemmmy** [comment]
some ideas:
- dump it into a file in the server directory for the admin to analyse
- upload it to a website for 30 minutes, similar to all the sponge performance tools. requires a backend tho

**Comment by SquidDev** [comment]
I've chucked a <kbd>feedback-wanted</kbd> label on this, as I'm feeling increasingly iffy about it. I feel it would be better to implement some sort of on-computer diagnostic tools rather than providing tools for server admins.

I personally see `/computercraft track` and friends as a way of localising the problem to a specific computer. *Fixing* slow programs is a whole 'nother issue, and something relevant for everyone.
