### ISSUE TITLE
Dungeon loot chests no-longer generate treasure disks inside them

### ISSUE THREAD

**Issue by GamesArsenal96** [SquidDev-CC/CC-Tweaked#432]
- Forge Version: 1.15.2-forge-31.1.41
- CC-Tweaked Version: [1.15.2] 1.87.1

Before 1.9 when loot tables were introduced ComputerCraft would generate "treasure disks" in the dungeon loot chests LootTable: "minecraft:chests/simple_dungeon" it was always interesting to discover these disks in the chests and also loot through the code.
![7zFM-09-40-29 PM](https://user-images.githubusercontent.com/24835664/80557201-beaa7600-899b-11ea-8c14-61acd7f245e4.png)

The disk files are still in the code but wondering is they can be readded into the original loottables

**Comment by GamesArsenal96** [comment]
Another thing is why is the redstone API on pocket computers?

Should I make an issue for that or?

**Comment by SquidDev** [comment]
I'm fairly sure this is intentional. I definitely remember Dan saying they were considered deprecated, though I'd need to dig up where. Though whether that's because he didn't want to wrangle loot tables or just not happy with them I don't know. 

I guess it's not a terrible idea to go through the programs, see which ones still work, and add them back. We'll see... 

> why is the redstone API on pocket computers?

I think some programs make the assumption that it will always be there, and so we can't remove it without breaking backwards compatibility. I realise it's a little absurd, but that's where we're stuck :).

**Comment by lupus590** [comment]
> Dan saying they were considered deprecated

https://github.com/dan200/ComputerCraft/pull/279#issuecomment-303706472

**Comment by SquidDev** [comment]
Thanks! Was too lazy to try to go digging on mobile :p.

**Comment by GamesArsenal96** [comment]
Ah, thank you :)

Also, if that is the case. The treasure disk is still an item in-game but with no data so that would need to be removed if removing will happen

**Comment by SquidDev** [comment]
One possibility would be to keep the item and move the resources and loot table to an external data pack. This means one could add back the treasure disk functionality, without any programs being part of the main mod.

**Comment by SquidDev** [comment]
I've implemented support for the above in 9f87eda5def567372398a34f675a948431ca9ff5. One may define a `data/computercraft/loot_tables/treasure_disk.json` loot table, and they'll be loaded in in the standard dungones.

I've also extracted the existing treasure disks into [a separate datapack](https://github.com/SquidDev-CC/treasure-disks). As of the next release, it should be possible to just drop that into a save and have the treasure disks generate.
