### ISSUE TITLE
add unicode/utf8 support from an pullrequest in dan200/computercraft

### ISSUE THREAD

**Issue by devomaa** [SquidDev-CC/CC-Tweaked#435]
https://github.com/dan200/ComputerCraft/pull/532

**Comment by Lemmmy** [comment]
I'm concerned about how this would interact with #409 - we're essentially doubling down on being single-byte, fantasy console style.

**Comment by SquidDev** [comment]
While unicode terminal support would be fantastic, at this point I can't see an obvious way to do it without either duplicating an awful lot of functionality or introducing breaking changes.

If someone can some up with a reasonable design for how to approach this, it might be worth looking into, but as it stands it's not really sane.

**Comment by neumond** [comment]
Unicode support imposes lots of problems since many characters are wide (emoji, japanese, chinese symbols) and must take 2 character places. This makes it especially problematic if one sets cursor position in the middle of such character and writes something. OpenComputers terminal code has lots of quirks with these wide characters.

**Comment by Lemmmy** [comment]
I agree. Part of the beauty of CC is the simplicity. While it's not as simple as, say, a run of the mill fantasy console, it's still very easy to work with and to understand (by design!), and bringing the endless quirks of Unicode is going to cause problems even for jedi
