### ISSUE TITLE
Cable covers

### ISSUE THREAD

**Issue by Lupus590** [SquidDev-CC/CC-Tweaked#451]
A way to hide cables in other blocks, maybe as simple as right clicking a non-tile entity block onto the cable.

**Comment by SquidDev** [comment]
I'd rather avoid adding a cover system directly to CC, as oh boy there's so much hidden complexity.

The cleanest thing to do is probably what we've done for wireless modems and add support for [MCMultipart]<sup>1</sup>. However, there's definitely some issues here:
 - Cables basically implement their own half-baked multipart system (as we have a cable and wired modem), and so some concepts don't map as well.
 - The bounding box of cables changes due to neighbouring blocks.

1: It might also be worth doing CBMP support (like CCTweaks had), but it's a lot of effort for very little gain.

[mcmultipart]: https://github.com/amadornes/MCMultiPart

**Comment by Lemmmy** [comment]
In terms of working with what we've got, I often find it useful when building to use the full block modems to go through walls etc. It looks much cleaner than there being a hole in the wall for a cable to go through

**Comment by lupus590** [comment]
but what do you do if you want to run cables in the floor and you don't have space to put them under the floor?

**Comment by Akxe** [comment]
@SquidDev  How about adding native compatibility of [Applied Energistics P2P Tunnel](https://ae-mod.info/P2P-Tunnel/)? This would add the ability to have "invisible" cables via AE2 cover system without adding much complexity to Computer Craft itself.

**Comment by SquidDev** [comment]
Sadly I don't think this is possible - the behaviour of P2P tunnels is hard-coded, so we can't add new types with custom behaviour. 

That said, Plethora used to have XNet support, which does enable facades. I guess it might be worth bringing that back. It's not ideal, as you can't facade modems, but a step in the right direction.

**Comment by SquidDev** [comment]
I think given the current state of multipart APIs, this isn't really possible. MCMP and FMP are both dead, and the only 1.15/16 API I can find is for Fabric :D:.

If there's alternative APIs available in the future I'm happy to reopen and look into this.
