### ISSUE TITLE
Blank white screen in computer console  

### ISSUE THREAD

**Issue by Dadstruction** [SquidDev-CC/CC-Tweaked#464]
Currently running Minecraft 1.15.2 on the Apex hosting service. 
Forge 1.15.2
cc-tweaked-1.15.2-1.88.1

Locally running forge 1.15.2-31.1.77 on a Mac (Retina 5K, 27-inch, 2017). 

I built a computer, but when going into the console, I can see the border, but the screen is completely white. I can give access if you want  to go in and replicate. 

<img width="1914" alt="Untitled 3" src="https://user-images.githubusercontent.com/13888203/83472217-b8089600-a454-11ea-83dd-40376818edd1.png">

[

## Useful information to include:
 - Minecraft version
 - CC: Tweaked version
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed.

**Comment by lupus590** [comment]
Can you get logs with the `log_computer_errors` config option enabled?

**Comment by SquidDev** [comment]
Graphical issues are the worst, as they're very system dependent. If you're able to, would you be able to try the following:

 - Try a fresh 1.15.2 install, with _just_ CC: Tweaked. It's possible there's another mod interfering with rendering.
 - If that doesn't work, can you test on Minecraft 1.12 or 1.14 with 1.86.2 and 1.88.0?

   1.88.0 uses the same rendering system as 1.15.2, but 1.86.2 uses an older version. Should just help me track down whether this issue is caused by 1.15.2 itself, or the rewrite.

**Comment by Dadstruction** [comment]
HUZZAH! 
My son was messing around on the server from his computer, which I'd set up after mine. He built a computer and had no problems. I updated to the latest forge with no effect, but when I replaced Tweaked 1.87.1 with 1.88.1, problem solved! 

Thanks for taking over this amazing mod. Keep up the good work!

**Comment by SquidDev** [comment]
Ahh, so this was a version mismatch. That's very odd, I thought that was prevented. I'll have to double check.

Thanks for the follow up though, glad you've got it fixed :).
