### ISSUE TITLE
Crash on custom 1.16.1 forge modpack

### ISSUE THREAD

**Issue by NxD136** [SquidDev-CC/CC-Tweaked#502]
Could be due to other mods, not the greatest at reading crash reports. Please help me out.

**Error message :** 
`The game crashed whilst initializing game
Error: java.lang.NullPointerException: Registry Object not present: computercraft:disk`

**Crash report :** 
[crash-2020-07-19_02.57.17-client.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/4943354/crash-2020-07-19_02.57.17-client.txt)

**Comment by SquidDev** [comment]
Can you include your full log? I _suspect_ there's an error happening earlier on which is causing this problem - there's no reason an item should fail to register.

**Comment by SquidDev** [comment]
Wrong issue, sorry!

**Comment by wieselkatze** [comment]
So after a lot of testing, as I had the same issue, it turns out this bug is due to, or at least related to [Titanium](https://github.com/InnovativeOnlineIndustries/Titanium) used as a library mod by [Industrial Foregoing](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing).
This can also be isolated by loading _just_ CC:Tweaked and Titanium. Same crash.
It's already throwing a lot of errors during startup:
[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/4994878/latest.log)
I had to experiment a lot with Forge versions as currently, they are apparently changing a lot and frequently remove and rename methods.
This was tested on Forge 32.0.96

**Comment by SquidDev** [comment]
I'm fairly sure this is a Titanium issue - they're registering event listeners incorrectly, which is causing the mod bus to crash.

It's probably worth reporting this to them. I assume you get still get some errors when launching with _just_ Titanium?

**Comment by wieselkatze** [comment]
After a lot more testing, it seems like this is not a CC issue, but rather has to do with how Forge loads mods. This does not _only_ happen with Titanium, but a lot of mods, like Immersive Engineering, RS Gauges & Switches etc..
_If you update to Forge 32.0.97, the game correctly prevents a startup saying mod X failed to load correctly_ instead of crashing with the computercraft:disk error.
So all in all it just is due to mod and Forge version incompatabilities in this whole 1.16 mess (as I would call it as of now).

**Comment by wieselkatze** [comment]
> 
> 
> I'm fairly sure this is a Titanium issue - they're registering event listeners incorrectly, which is causing the mod event bus to crash. Forge doesn't always handle this gracefully, and so you get crashes later on in the load in pipeline.
> 
> It's probably worth reporting this to them. I assume you get still get some errors when launching with _just_ Titanium?

I just tested - if you launch on Forge 32.0.96 with only Titanium, the game also correctly says it failed to load Titanium correctly.
The issue only is adding CC:T to the mix, as the crash report falsely 'accuses' CC:T of the crash
