### ISSUE TITLE
Duplicate recipe

### ISSUE THREAD

**Issue by lachiu** [SquidDev-CC/CC-Tweaked#532]
Useful information to include:
 - Modpack The Classic Pack - https://www.technicpack.net/modpack/tc-redux.786294
 - Sponge version 1.12.2
 - CC: Tweaked version 1.85/1.80
 - Logs: Not sure if it's needed.
 - Detailed reproduction steps: Use cc-tweaked 1.85 for sponge 1.12.2.

Craftable one: (check the EMC value (by removing projecte folder of said modpack you get the defaults)
![](https://cdn.discordapp.com/attachments/477911902152949771/748655481081561169/unknown.png)

Uncraftable one, yet 32 emc more
![](https://cdn.discordapp.com/attachments/477911902152949771/748655543325032538/unknown.png)

The mining turtle for instance uses the uncraftable one.
![](https://cdn.discordapp.com/attachments/477911902152949771/748655618834825297/unknown.png)

CraftTweaker says it's either CC-Tweaked or the modpack.
![](https://image.prntscr.com/image/aC_v1oeqTxC4Xcn9gRJezA.png)

Uncraftable one - Craftable one, in that order.
![](https://cdn.discordapp.com/attachments/209790204322512896/748666854381191238/unknown.png)

Upon placing and mining the craftable one I get the uncraftable one. ComputerCraft 1.80 didn't have this.

**Comment by SquidDev** [comment]
This is a problem with the modpack's CraftTweaker scripts. They unregister a recipe for `computercraft:turtle_extended`, but the incorrectly register one for `computercraft:turtle`. This is no longer used within the mod's code and exists only for world-compatibility reasons.

```zenscript
recipes.remove(<computercraft:turtle_expanded>);
recipes.addShaped(<computercraft:turtle>,
  [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], 
   [<ore:ingotIron>, <computercraft:computer>, <ore:ingotIron>], 
   [<minecraft:iron_ingot>, <ore:chest>, <ore:ingotIron>]]);
```

There's also some weird stuff going on with crafty turtles, but I'm afraid I don't understand that at all.

**Comment by lachiu** [comment]
recipes.remove(<computercraft:turtle_expanded>);
recipes.remove(<computercraft:turtle_advanced>);
recipes.addShapeless(<computercraft:turtle_expanded>.withTag({leftUpgrade: 2 as short}), [<computercraft:turtle>, <minecraft:crafting_table>]);
recipes.addShapeless(<computercraft:turtle_advanced>.withTag({leftUpgrade: 2 as short}), [<computercraft:turtle_advanced>, <minecraft:crafting_table>]);

recipes.addShaped(<computercraft:turtle_advanced>,			[[<ore:ingotGold>, <ore:ingotGold>, <ore:ingotGold>], 
                                             [<ore:ingotGold>, <computercraft:computer:16384>, <ore:ingotGold>], 
											 [<ore:ingotGold>, <ore:chest>, <minecraft:gold_ingot>]]);

recipes.addShaped(<computercraft:turtle>,			[[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], 
                                             [<ore:ingotIron>, <computercraft:computer>, <ore:ingotIron>], 
											 [<minecraft:iron_ingot>, <ore:chest>, <ore:ingotIron>]]);

These were there already.

**Comment by Pulz-TCP** [comment]
You were told to remove the portions of the script that add/register new recipes- hence the duplicated JEI entry, as it is no longer used within the mods code.

**Comment by SquidDev** [comment]
Well, really that `computercraft:turtle` needs to be replaced with `computercraft:turtle_extended`. But this is something you should probably report to the pack authors instead of trying to change yourself.

**Comment by Pulz-TCP** [comment]
@lachiu 

You are running a modified version of my modpack. Without your modifications, my modpack runs and operates completely fine. @SquidDev has (thank you) pointed out that obviously my old 'turtle fixes' are actually problematic and no longer required anyway. But contrary to what he said, please do not contact me asking me to fix issues you have introduced yourself! I do not currently have the free time to investigate customization made by individuals.

The bad recipe only introduces one issue: some turtle types appear as CRAFTY TURTLE in their JEI entry (crafty turtles just have the name 'turtle' in JEI). I have just tested the modpack and see why nobody has reported turtle issues to me: **all turtle types remain fully craftable despite appearing as CRAFTY TURTLE's in JEI.**
CRAFTY TURTLE's have an extra 32 emc compared to the regular ones, as they are made with a crafting table (4 planks, 8 emc each 4*8=32). So that is where your magic 32 emc is coming from. But again, this is purely visual in JEI and the modpack does not have EMC values for turtles by default anyway. 

I haven't got time to load up CC:Tweaked today, but I am fairly sure that the extent of your issue is purely visual and in JEI only. With that said, I have already removed the recipe- you can make the same modifications manually as https://github.com/Pulz-TCP/TheClassicPack/commit/dcb5dfd9692bf3959fa7c0c1006cd5f72ab6d03f
