### ISSUE TITLE
turtle.placeDown() with shears

### ISSUE THREAD

**Issue by Minecraft2p0** [SquidDev-CC/CC-Tweaked#537]
The command turtle.placeDown () works since the update. Unfortunately, the cut wool is now deleted immediately and is not available to the turtle in the inventory. Unfortunately, the command is of no use.

Translated with Google

**Comment by SquidDev** [comment]
That should be fixed now.

In the future, would it be possible to include a bit more information in the issue - it took me far too long to work out you were trying to sheer sheep. I realise English isn't your first language, but a poorly translated description is better than none at all!

I don't know if the issue template shows up for you, but it's also useful to include your Minecraft and CC:T version in the report - otherwise I have to guess.

**Comment by Minecraft2p0** [comment]
does that mean there is another update?

I will try to provide more and clear information in the future.

I am using the MC version 1.16.2 with the latest CC: T Mod.

**Comment by Minecraft2p0** [comment]
Thanks a lot for your time.
