### ISSUE TITLE
Edit launches scripts in the wrong directory

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#552]
When using the "Run" option from `edit`, we save to a file called `/.temp` and run it:

https://github.com/SquidDev-CC/CC-Tweaked/blob/30d35883b83831900b34040f0131c7e06f5c3e52/src/main/resources/data/computercraft/lua/rom/programs/edit.lua#L392-L397

Historically this was fine, but is more problematic now that `require` exists. As the package path relies on the directory the program is stored in, packages may not be found.

There's a couple of possible solutions to this:
 - Save the file in the script's directory iff the directory isn't read only.
 - Write a bootstrap script which then loads the program and uses `cc.require` to bootstrap a new package environment.

Neither are going to be perfect - ideally we'd even be able to fake `getRunningProgram`, but they might work. Ideas welcome!

**Comment by Luca0208** [comment]
> Neither are going to be perfect - ideally we'd even be able to fake getRunningProgram, but they might work. Ideas welcome!

It might be worth taking a look at how [trace](http://www.computercraft.info/forums2/index.php?/topic/27844-trace-simple-stack-traces-for-errors/) deals with this stuff, in [L.47f](https://pastebin.com/CYQp63kb) it modifies the shell in the environment to return the correct value for `shell.getRunningProgram` I imagine something similar would work for this as well.

Although, since multishell is unable to launch a function directly, we'd still need to write to a .temp file with some sort of wrapper around it.

**Comment by SquidDev** [comment]
> In L.47f it modifies the shell in the environment to return the correct value for `shell.getRunningProgram` I imagine something similar would work for this as well.

OK, that's horrific.

**Comment by SquidDev** [comment]
I think the above commit fixes this as much as is really possible for now.
