### ISSUE TITLE
Monitor Rendering Bug

### ISSUE THREAD

**Issue by triffman33** [SquidDev-CC/CC-Tweaked#599]
- Minecraft version: 1.16.4
 - CC: Tweaked version: cc-tweaked-1.16.4-1.94.0.jar
 - Log: [latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/5654282/latest.log)

 - Detailed reproduction steps: Place monitor and sometimes things like water get rendered infront of it when it should be blocked by the monitor being there. https://www.youtube.com/watch?v=Vk5_1Aw3UEQ

**Comment by SquidDev** [comment]
This is a very odd bug. I'm not 100% sure why this would happen - we render to the depth buffer like any other block, so it shouldn't be overridden.

I'm afraid I've tried several setups, and I'm unable to get this to occur on my computer at all. Just a couple of things I want to check to see if I can nail down the problem:

 - Just to confirm, you're facing south in the above video? Does this actually make a difference, or does this problem happen in all directions.
 - Does it still occur if you place the reactor blocks with a boring one (such as dirt)?
 - Could you take a screenshot with chunk boundaries enabled (F3+G)?

**Comment by triffman33** [comment]
Yep south seems to be the only direction where it happens, it still occurs with normal blocks or with no blocks at all. 
https://www.youtube.com/watch?v=gMwcfWLxlDs should show more info on the setup. Also items seem to render behind it as well as water, but not items of blocks dropped. I removed every other mod this time and it still occurs so i guess it's either forge or cc:tweaked.

**Comment by SquidDev** [comment]
Thank you, that's very helpful! Turns out I was testing on 1.15 (where it doesn't happen), but can easily reproduce on 1.16.

This appears to be a a problem with any transparent block, not just water.

Interestingly, it's much, much worse in spectator mode.

![A monitor with glass being rendered through it](https://user-images.githubusercontent.com/4346137/101887571-fa91f480-3b94-11eb-8d26-598e4bd2301b.png)

I guess something changed in the render engine's internals which means the blocker is either rendered much later, or not at all.
