### ISSUE TITLE
Too bright monitors with Shader

### ISSUE THREAD

**Issue by Maar10tech** [SquidDev-CC/CC-Tweaked#612]
Hello,
I tried a lot Shaders, but I had the same issue in all of them:
I asume monitors are recognized as a lightning source, such as Glowstone or Panels from AE2, so colors.black is with the Shader more a bright gray, and white or yellow are as bright as light sources and so I can't use them as background or text coulours, because the brightness makes them unreadable.
Maybe it would be possible to add a version without these lightning effects in monitor blocks.
Sadly nobody from the shader dev-team replied, so I have high hopes here.

I'm playing on a server with these configurations:
forge 1.16.4 - 35.1.0
Shader: BSL

I hope you can help,
Greetings

**Comment by SquidDev** [comment]
Can you post a screenshot of what it looks like right now? Just curious - monitors are always funky with shaders, but not seen this before. Just to confirm, you are using the [VBO monitor renderer](https://github.com/SquidDev-CC/CC-Tweaked/wiki/Monitor-renderers)?

Monitors don't act as light sources - you can confirm this by placing them in a dark room. However, they do render "full bright" (as you mention, like panels from AE2). This has historically caused issues with Optifine (sp614x/optifine#417, MightyPirates/OpenComputers#2486, etc...), though I hoped this would be fixed in 1.16.

I would recommend filing a bug with Optifine directly (with screenshots, logs, etc...). While I can bodge in a workaround, [I imagine there's still going to be problems with dozens of other mods](https://github.com/search?q=language%3Ajava+lightmap%28LIGHTMAP_DISABLED%29&type=code).

**Comment by Maar10tech** [comment]
I'm embarrassed I haven't seen this config earlier.
Fixed the problem, altough it cots a few fps.
Thanks a lot and sorry for interrupting!

**Comment by SquidDev** [comment]
Oh, wonderful. Glad that has fixed it!
