### ISSUE TITLE
Computercraft FTB Revelation Problem

### ISSUE THREAD

**Issue by SevenGlitch** [SquidDev-CC/CC-Tweaked#631]
Hello, i have been playing on a whitelisted FTB Revelation server and i came across this problem, when i try to download something from the pastebin it will get stuck at "Connecting to pastebin.com..." and it will stay there until i terminate it manually. The server has enabled https but it still hasn't changed anything.
![εικόνα](https://user-images.githubusercontent.com/49343667/103162077-de788f00-47f3-11eb-8cb6-506afe83c677.png)

**Comment by Lupus590** [comment]
Can you post the CC version? Or at least the mod pack version?

**Comment by SquidDev** [comment]
I can't reproduce on the latest CC: Tweaked. FTB revelations is 1.12.2, which is unsupported, but nothing has changed in the HTTP code since then.

I can't think of a reason that the connection would stall indefinitely like this. If Pastebin were blocking you, there'd still be an error. 

It might be worth running `http.get("https://pastebin.com/raw/gkz5sgZ8")` in the Lua shell, and seeing if that ever returns. Would at least help narrow down the problem.

**Comment by SevenGlitch** [comment]
> 
> 
> I can't reproduce on the latest CC: Tweaked. FTB revelations is 1.12.2, which is unsupported, but nothing has changed in the HTTP code since then.
> 
> I can't think of a reason that the connection would stall indefinitely like this. If Pastebin were blocking you, there'd still be an error.
> 
> It might be worth running `http.get("https://pastebin.com/raw/gkz5sgZ8")` in the Lua shell, and seeing if that ever returns. Would at least help narrow down the problem.

Well i did do that but it just get stack and does nothing and writes nothing.

**Comment by SevenGlitch** [comment]
The Modpack version is 3.3.0

**Comment by Lupus590** [comment]
Tested on modpack version 3.4.0, could not reproduce. The file that Squid linked downloaded just fine with the snippet and the pastebin command.
