### ISSUE TITLE
Events are not documented on tweaked.cc

### ISSUE THREAD

**Issue by Lupus590** [SquidDev-CC/CC-Tweaked#640]
That or I didn't find them where I was expecting to find them.

**Comment by SquidDev** [comment]
This is largely blocked by #565, which in turn is blocked by some illuaminate work. Never thought I'd miss JIRA and it's additional issue fields.

The actual work in question (getting illuaminate to understand markdown files and process them in the doc system) is a wee bit more complex than I was expecting, because I'm apparently determined to over-engineer it.

**Comment by SquidDev** [comment]
As mentioned in #565, this is now unblocked. I've pulled in @BradyFromDiscord's docs on the interaction events, but probably worth adding the rest of them. If people are willing to help, that'd be fantastic.
