### ISSUE TITLE
Netty - Error handling HTTP response

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/CC-Tweaked#642]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/16393543/103447793-bf8b5a00-4c44-11eb-82c9-39d4dcb4fd19.png">

When checking the URL, everything evaluates fine, but when I attempt to run a GET request, Netty logs an error. See latest.log below.

## Useful information to include:
 - MC: 1.16.4
 - CC:T: 1.95.0
 - [latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/5759553/latest.log)
 - Detailed reproduction steps: Follow what the image above 

Edit: It's also probably relevant that I'm using MacOS Big Sur Version 11.1

**Comment by Zyano** [comment]
I believe this happens because Lets Encrypts root certificates are not part of trusted root certificates list. 
If that's the case then there is nothing the mod devs should do to fix it (IMO). As a server owner it should be possible to update the JAVA root certificate store to include the Lets Encrypt root certificates.

All of this will depend on the version of JAVA being used on the server as you can read from here:
https://letsencrypt.org/docs/certificate-compatibility/

Digging through the logs a bit more it does appears that forge attempts fix this issue as can be seen in line 3:
[01Jan2021 15:16:28.138] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust

I have no idea how this attempts to fix the issue so it may only apply to specific classes designed by forge. 

From personal experience with OpenComputers on FTB University the issue is solvable by updating the JAVA Trusted Root Certificates (keystore) manually. 

I hope this helps.

**Comment by Lupus590** [comment]
Updating my java version fixed it for me.

**Comment by hugeblank** [comment]
Since this is a dupe I'll close it. 

Redirecting the launcher to a different java executable did fix the problem.
