### ISSUE TITLE
Registry Object not present: computercraft:disk

### ISSUE THREAD

**Issue by Shuckes** [SquidDev-CC/CC-Tweaked#686]
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Registry Object not present: computercraft:disk
Exit Code: -1

CC: Tweaked 1.15.2 1.95.2
doesnt work with MineColonies or doesnt work at all.

**Comment by SquidDev** [comment]
Thank you for the report! Would you be able to fill out the information in [this template](https://github.com/SquidDev-CC/CC-Tweaked/blob/mc-1.15.x/.github/ISSUE_TEMPLATE/bug_report.md)?

Especially useful would be the log files - this problem happens when there's an earlier mod loading issue, so it's hard to tell what that'd be without more context.

**Comment by ARP-Equilibrated** [comment]
Crash is not localized to MineColonies. I got the same crash. Log attached.

-----

Minecraft Version: 1.15.2
Forge Version: 31.2.47
CC: T Version: 1.95.2
Log: 
[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/5860805/latest.log)

Reproduction steps & Info:
Mod List: 
![modlist](https://user-images.githubusercontent.com/77896335/105610839-c870d680-5d7f-11eb-9f8b-15d3ec8b490f.png)

[ ] 1. Launch Forge
[ ] 2. Observe crash

-----

**Comment by SquidDev** [comment]
@ARP-Equilibrated I may be missing something, but I can't actually see CC: Tweaked on that mod list. It's definitely not showing up in the logs, though I guess that's not an indication of anything.

Also, please delete your `options.txt` file to regenerate it. The parsing exceptions from those are no fun at all :).

**Comment by Arekenaten** [comment]
Just wanted to add on that this is happening with just a forge and cc-tweaked install. 
[crash-2021-01-23_16.23.07-client.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/5861063/crash-2021-01-23_16.23.07-client.txt)

First time trying a single install on linux so I may have done something wrong but...

**Comment by SquidDev** [comment]
Right, it appears there's a class loading error previously in the load path:

```
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: dan200.computercraft.shared.pocket.items.ItemPocketComputer.func_210306_e(Lnet/minecraft/item/ItemStack;Lnet/minecraft/world/World;Lnet/minecraft/entity/LivingEntity;)F
	at dan200.computercraft.shared.pocket.items.ItemPocketComputer.<clinit>(ItemPocketComputer.java:411)
	at dan200.computercraft.shared.Registry$ModItems.lambda$static$1(Registry.java:203)
	at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:84)
	at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:117)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
```

Looking at the decompiled class code, the lambdas in `ItemPocketComputer` get compiled to the following (obviously bogus) code. 

```java
private static final IItemPropertyGetter COMPUTER_STATE = ItemPocketComputer::func_210306_e;
private static final IItemPropertyGetter COMPUTER_COLOURED = ItemPocketComputer::func_210307_d;
```

I imagine this is being caused by a combination of 34b5ede326e913676b6f538408e3f82504159c76 and some underlying bugs in ForgeGradle. We may have to revert that commit (ughr), or try to narrow down the underlying issue.

I'll archive the build on CF fow now, so other people aren't hit by it.

**Comment by Arekenaten** [comment]
Glad to have helped narrow it down. Any further information that could be useful?

**Comment by ARP-Equilibrated** [comment]
@SquidDev Yeah I took the mod out when it was causing issues, but that was the report from when I had it in. All the mods shown there were with CC: T.
