### ISSUE TITLE
Add advancements to guide through the mod progression

### ISSUE THREAD

**Issue by Jummit** [SquidDev-CC/CC-Tweaked#733]
This is just an Idea; I've created a datapack for my own playthrough, but maybe it could be added to the mod as well. What do you think?

![image](https://user-images.githubusercontent.com/28286961/110209444-f4a66980-7e8c-11eb-8e5d-f8c70334fc8c.png)

[computer_craft_advancements.zip](https://github.com/SquidDev-CC/CC-Tweaked/files/6095503/computer_craft_advancements.zip)

**Comment by SquidDev** [comment]
I thought about this when the advancement system was first revamped, and rather came to the conclusion that CC doesn't really have enough content to make it worthwhile.

As I see it, there's two points of the advancement system:
 - Guide people through the game/mod, giving some indication of the progression tree and what content is available.
 - Reward people for actual achievements. So things like visiting every biome, killing a skeleton at 50m, etc...

As far as the first bullet point goes, IMO you should only really be highlighting the milestones, not every step of the journey. For instance, one only really needs "craft a computer" -> { "craft a turtle", "craft a pocket computer"} (accepting both normal or advanced ones) - the intervening steps can be filled in with the existing recipe advancements.

The issue is that really that's as far as CC's progression tree goes. The rest of it (i.e. peripherals) is pretty flat, which means there's not really any milestones to reach, short of going for a Pokemon-esque "~catch~ craft them all".

As far as actual achievements goes, that's much harder to handle. There's all sorts of impressive things you can do with CC, but how does one measure that they've been done?

**Comment by Jummit** [comment]
Yep, that about sums up my thoughts as well. I myself enjoy the little popups when I progress, and it gives you a nice overview of what you have done and what you have left to do. But I agree that it doesn't really fit into the base mod.
