### ISSUE TITLE
this is a questies

### ISSUE THREAD

**Issue by zaze06** [SquidDev-CC/CC-Tweaked#773]
sens I can't make an account on the computer craft website and I'm banned to make questions on StackOverflow I'm asking to hear

How can I get the first item in the inventory that isn't on a list?

and yes I will try to fix the problem whit StackOverflow

**Comment by Lupus590** [comment]
This would have been better as a [discussion](https://github.com/SquidDev-CC/CC-Tweaked/discussions) instead of an issue.

There are new forums: https://forums.computercraft.cc/index.php

Discord is also a thing: https://discord.computercraft.cc/

Also, please work on your spelling, I can understand that it can be difficult if English is not your first language. You might find [Grammarly](https://app.grammarly.com/) helpful.
