### ISSUE TITLE
Paper Shader problem

### ISSUE THREAD

**Issue by MAGGen-hub** [SquidDev-CC/CC-Tweaked#906]
### Minecraft Version

1.16.x

### Version

1.98.1

### Details

I use chocapic based shaders (chocapic | BSL | ArtraLex | etc.) and for some reason paper becomes extremly bright when I place it in frame. It's hard to read something on it and I can see it from realy far away like lamps and other glowing things. I know thats this is not your problem but if you can - please fix it...
It looks normal in hands... only frame problem:
![image](https://user-images.githubusercontent.com/56871670/130792072-a1b917a9-d796-4079-8fe4-258c3bbe8efc.png)

Thank you for you attantion.

**Comment by MAGGen-hub** [comment]
If you know how I can fix it (editing shaders algoritm) please tell me. Thanks.

**Comment by MAGGen-hub** [comment]
Also I get this "water problem" and transpanent poket pc... But it's em... "normal" for me.
![image](https://user-images.githubusercontent.com/56871670/130792814-c0480a91-1428-4819-a754-5882b8dcf9d7.png)

**Comment by MAGGen-hub** [comment]
Maps and other map-like stuff working normaly.

**Comment by SquidDev** [comment]
> If you know how I can fix it (editing shaders algoritm) please tell me. Thanks.

Switching to vanilla shaders? :p.

In all seriousness, I'm afraid I'm not going to fix this. Rendering issues are hard to debug at the best of times, and adding adding shaders and Optifine into the mix makes things basically impossible to debug, especially due to their closed-source nature.

I've spent a lot of hours trying to fix issues with shaders in the past, and it rarely comes to anything. I'm afraid I just can't justify any more time of this sort of stuff.

It might be worth raising issues with the shader author (or Optifine if it happens with other shaders too). I'm happy to incorporate any fixes they might suggest.
